#!/usr/bin/env python
# CFD General Notation System - CGNS XML tools
# ONERA/DSNA - poinot@onera.fr - henaux@onera.fr
# pyCCCCC - $Id: c5 22 2005-02-02 09:57:08Z  $
#
# See file COPYING in the root directory of this Python module source 
# tree for license information. 
#
# ------------------------------------------------------------
import CCCCC.tools.ccccc

# ------------------------------------------------------------
if (__name__ == "__main__"):
  CCCCC.tools.ccccc.go()
