#!/usr/bin/env python
# CFD General Notation System - CGNS XML tools
# ONERA/DSNA - poinot@onera.fr - henaux@onera.fr
# pyCCCCC - $Id: crnc2rng 22 2005-02-02 09:57:08Z  $
#
# See file COPYING in the root directory of this Python module source 
# tree for license information. 
#
import CCCCC.tools.rnc2rng.rt as trang
import getopt
import sys
import os.path

fileinputname=""
fileoutputname=""
force=0

opts, args = getopt.getopt(sys.argv[1:],"fi:o:")
for o in opts:
    if ((o[0]=="-i") and not fileinputname):
        fileinputname=o[1]
    if ((o[0]=="-o") and not fileoutputname):
        fileoutputname=o[1]
    if (o[0] == "-f"):
        force=1

# ---------------------------------------------------------------------------
if (fileinputname and not (os.path.exists(fileinputname))):
    raise "Input file doesn't exist"
if (fileinputname):
    fileinput=open(fileinputname,'r')

# ---------------------------------------------------------------------------
if (fileoutputname and os.path.exists(fileoutputname) and not force):
    raise "Output file already exist, use -f to force overwrite"
if (fileoutputname):
    fileoutput=open(fileoutputname,'w+')

if (not fileinputname):   raise "No input file"
if (not fileoutputname):  raise "No output file"

trang.translate(fileinputname,fileoutputname)

# ---------------------------------------------------------------------------
