# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T/Q7MainWindow.ui'
#
# Created: Tue Nov 29 11:05:06 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Q7MainWindow(object):
    def setupUi(self, Q7MainWindow):
        Q7MainWindow.setObjectName("Q7MainWindow")
        Q7MainWindow.resize(793, 218)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(Q7MainWindow.sizePolicy().hasHeightForWidth())
        Q7MainWindow.setSizePolicy(sizePolicy)
        Q7MainWindow.setMinimumSize(QtCore.QSize(793, 218))
        Q7MainWindow.setMaximumSize(QtCore.QSize(793, 218))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/cgSpy.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7MainWindow.setWindowIcon(icon)
        Q7MainWindow.setWhatsThis("")
        self.centralwidget = QtGui.QWidget(Q7MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bResetScrollBars = QtGui.QToolButton(self.centralwidget)
        self.bResetScrollBars.setGeometry(QtCore.QRect(773, 202, 16, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bResetScrollBars.sizePolicy().hasHeightForWidth())
        self.bResetScrollBars.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/add.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bResetScrollBars.setIcon(icon1)
        self.bResetScrollBars.setObjectName("bResetScrollBars")
        self.Q7ControlTable = QtGui.QTableWidget(self.centralwidget)
        self.Q7ControlTable.setGeometry(QtCore.QRect(7, 36, 781, 181))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q7ControlTable.sizePolicy().hasHeightForWidth())
        self.Q7ControlTable.setSizePolicy(sizePolicy)
        self.Q7ControlTable.setMinimumSize(QtCore.QSize(781, 181))
        self.Q7ControlTable.setMaximumSize(QtCore.QSize(781, 181))
        self.Q7ControlTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.Q7ControlTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.Q7ControlTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.Q7ControlTable.setCornerButtonEnabled(False)
        self.Q7ControlTable.setRowCount(0)
        self.Q7ControlTable.setColumnCount(6)
        self.Q7ControlTable.setObjectName("Q7ControlTable")
        self.Q7ControlTable.setColumnCount(6)
        self.Q7ControlTable.setRowCount(0)
        self.bTreeLoad = QtGui.QToolButton(self.centralwidget)
        self.bTreeLoad.setGeometry(QtCore.QRect(7, 7, 25, 25))
        self.bTreeLoad.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/tree-load.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bTreeLoad.setIcon(icon2)
        self.bTreeLoad.setObjectName("bTreeLoad")
        self.bEditTree = QtGui.QToolButton(self.centralwidget)
        self.bEditTree.setGeometry(QtCore.QRect(40, 7, 25, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/tree-new.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bEditTree.setIcon(icon3)
        self.bEditTree.setObjectName("bEditTree")
        self.bPatternView = QtGui.QToolButton(self.centralwidget)
        self.bPatternView.setGeometry(QtCore.QRect(100, 7, 25, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/pattern.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bPatternView.setIcon(icon4)
        self.bPatternView.setObjectName("bPatternView")
        self.bOptionView = QtGui.QToolButton(self.centralwidget)
        self.bOptionView.setGeometry(QtCore.QRect(690, 7, 25, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/options-view.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bOptionView.setIcon(icon5)
        self.bOptionView.setObjectName("bOptionView")
        self.bAbout = QtGui.QToolButton(self.centralwidget)
        self.bAbout.setGeometry(QtCore.QRect(720, 7, 25, 25))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/view-help.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAbout.setIcon(icon6)
        self.bAbout.setObjectName("bAbout")
        self.bClose = QtGui.QPushButton(self.centralwidget)
        self.bClose.setGeometry(QtCore.QRect(760, 7, 25, 25))
        self.bClose.setMinimumSize(QtCore.QSize(25, 25))
        self.bClose.setMaximumSize(QtCore.QSize(25, 25))
        self.bClose.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icons/close-view.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bClose.setIcon(icon7)
        self.bClose.setObjectName("bClose")
        Q7MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Q7MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Q7MainWindow)

    def retranslateUi(self, Q7MainWindow):
        Q7MainWindow.setWindowTitle(QtGui.QApplication.translate("Q7MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.bResetScrollBars.setToolTip(QtGui.QApplication.translate("Q7MainWindow", "Reset scrollbars to left top corner of window", None, QtGui.QApplication.UnicodeUTF8))
        self.bResetScrollBars.setText(QtGui.QApplication.translate("Q7MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.Q7ControlTable.setSortingEnabled(True)
        self.bTreeLoad.setToolTip(QtGui.QApplication.translate("Q7MainWindow", "Load an existing CGNS file", None, QtGui.QApplication.UnicodeUTF8))
        self.bEditTree.setToolTip(QtGui.QApplication.translate("Q7MainWindow", "Create a new CGNS tree from scratch", None, QtGui.QApplication.UnicodeUTF8))
        self.bEditTree.setText(QtGui.QApplication.translate("Q7MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bPatternView.setToolTip(QtGui.QApplication.translate("Q7MainWindow", "Open CGNS/SIDS sub-trees database", None, QtGui.QApplication.UnicodeUTF8))
        self.bPatternView.setText(QtGui.QApplication.translate("Q7MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bOptionView.setToolTip(QtGui.QApplication.translate("Q7MainWindow", "Set user defined options", None, QtGui.QApplication.UnicodeUTF8))
        self.bOptionView.setText(QtGui.QApplication.translate("Q7MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bAbout.setToolTip(QtGui.QApplication.translate("Q7MainWindow", "About....", None, QtGui.QApplication.UnicodeUTF8))
        self.bAbout.setText(QtGui.QApplication.translate("Q7MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))

import Res_rc
