# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGNS/NAV/T/Q7OptionsWindow.ui'
#
# Created: Mon Sep 29 15:55:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Q7OptionsWindow(object):
    def setupUi(self, Q7OptionsWindow):
        Q7OptionsWindow.setObjectName("Q7OptionsWindow")
        Q7OptionsWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Q7OptionsWindow.resize(580, 364)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7OptionsWindow.sizePolicy().hasHeightForWidth())
        Q7OptionsWindow.setSizePolicy(sizePolicy)
        Q7OptionsWindow.setMinimumSize(QtCore.QSize(580, 364))
        Q7OptionsWindow.setMaximumSize(QtCore.QSize(580, 364))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/cgSpy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7OptionsWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Q7OptionsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabs = QtGui.QTabWidget(Q7OptionsWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setMinimumSize(QtCore.QSize(560, 310))
        self.tabs.setMaximumSize(QtCore.QSize(560, 310))
        self.tabs.setObjectName("tabs")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.__O_recursivetreedisplay = QtGui.QCheckBox(self.tab_1)
        self.__O_recursivetreedisplay.setGeometry(QtCore.QRect(10, 15, 274, 22))
        self.__O_recursivetreedisplay.setObjectName("__O_recursivetreedisplay")
        self.__O_recursivesidspatternsload = QtGui.QCheckBox(self.tab_1)
        self.__O_recursivesidspatternsload.setGeometry(QtCore.QRect(10, 230, 274, 22))
        self.__O_recursivesidspatternsload.setObjectName("__O_recursivesidspatternsload")
        self.__O_donotdisplaylargedata = QtGui.QCheckBox(self.tab_1)
        self.__O_donotdisplaylargedata.setGeometry(QtCore.QRect(10, 120, 274, 22))
        self.__O_donotdisplaylargedata.setObjectName("__O_donotdisplaylargedata")
        self.__O_followlinksatload = QtGui.QCheckBox(self.tab_1)
        self.__O_followlinksatload.setGeometry(QtCore.QRect(10, 170, 274, 22))
        self.__O_followlinksatload.setObjectName("__O_followlinksatload")
        self.__O_donotfollowlinksatsave = QtGui.QCheckBox(self.tab_1)
        self.__O_donotfollowlinksatsave.setGeometry(QtCore.QRect(10, 210, 274, 22))
        self.__O_donotfollowlinksatsave.setObjectName("__O_donotfollowlinksatsave")
        self.__O_donotloadlargearrays = QtGui.QCheckBox(self.tab_1)
        self.__O_donotloadlargearrays.setGeometry(QtCore.QRect(10, 65, 274, 22))
        self.__O_donotloadlargearrays.setObjectName("__O_donotloadlargearrays")
        self.label_1 = QtGui.QLabel(self.tab_1)
        self.label_1.setGeometry(QtCore.QRect(10, 30, 217, 27))
        self.label_1.setObjectName("label_1")
        self.__O_maxrecursionlevel = QtGui.QSpinBox(self.tab_1)
        self.__O_maxrecursionlevel.setGeometry(QtCore.QRect(235, 20, 71, 27))
        self.__O_maxrecursionlevel.setMinimum(1)
        self.__O_maxrecursionlevel.setMaximum(99)
        self.__O_maxrecursionlevel.setProperty("value", 7)
        self.__O_maxrecursionlevel.setObjectName("__O_maxrecursionlevel")
        self.__O_maxloaddatasize = QtGui.QSpinBox(self.tab_1)
        self.__O_maxloaddatasize.setEnabled(True)
        self.__O_maxloaddatasize.setGeometry(QtCore.QRect(235, 70, 71, 27))
        self.__O_maxloaddatasize.setMinimum(-1)
        self.__O_maxloaddatasize.setMaximum(65535)
        self.__O_maxloaddatasize.setProperty("value", -1)
        self.__O_maxloaddatasize.setObjectName("__O_maxloaddatasize")
        self.__O_stoploadbrokenlinks = QtGui.QCheckBox(self.tab_1)
        self.__O_stoploadbrokenlinks.setGeometry(QtCore.QRect(10, 190, 274, 22))
        self.__O_stoploadbrokenlinks.setObjectName("__O_stoploadbrokenlinks")
        self.__O_filterhdffiles = QtGui.QCheckBox(self.tab_1)
        self.__O_filterhdffiles.setGeometry(QtCore.QRect(320, 10, 274, 22))
        self.__O_filterhdffiles.setObjectName("__O_filterhdffiles")
        self.__O_filtercgnsfiles = QtGui.QCheckBox(self.tab_1)
        self.__O_filtercgnsfiles.setGeometry(QtCore.QRect(320, 80, 274, 22))
        self.__O_filtercgnsfiles.setObjectName("__O_filtercgnsfiles")
        self.line = QtGui.QFrame(self.tab_1)
        self.line.setGeometry(QtCore.QRect(300, 10, 20, 261))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.__O_cgnsfileextension = QtGui.QPlainTextEdit(self.tab_1)
        self.__O_cgnsfileextension.setGeometry(QtCore.QRect(335, 100, 211, 41))
        self.__O_cgnsfileextension.setObjectName("__O_cgnsfileextension")
        self.__O_hdffileextension = QtGui.QPlainTextEdit(self.tab_1)
        self.__O_hdffileextension.setGeometry(QtCore.QRect(335, 30, 211, 41))
        self.__O_hdffileextension.setObjectName("__O_hdffileextension")
        self.label_23 = QtGui.QLabel(self.tab_1)
        self.label_23.setGeometry(QtCore.QRect(10, 135, 217, 27))
        self.label_23.setObjectName("label_23")
        self.__O_maxdisplaydatasize = QtGui.QSpinBox(self.tab_1)
        self.__O_maxdisplaydatasize.setGeometry(QtCore.QRect(235, 125, 71, 27))
        self.__O_maxdisplaydatasize.setMinimum(-1)
        self.__O_maxdisplaydatasize.setMaximum(1000)
        self.__O_maxdisplaydatasize.setProperty("value", -1)
        self.__O_maxdisplaydatasize.setObjectName("__O_maxdisplaydatasize")
        self.label_9 = QtGui.QLabel(self.tab_1)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 217, 27))
        self.label_9.setObjectName("label_9")
        self.__O_fileupdateremoveschildren = QtGui.QCheckBox(self.tab_1)
        self.__O_fileupdateremoveschildren.setGeometry(QtCore.QRect(10, 250, 271, 21))
        self.__O_fileupdateremoveschildren.setObjectName("__O_fileupdateremoveschildren")
        self.tabs.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.__O_addcurrentdirinsearch = QtGui.QCheckBox(self.tab_2)
        self.__O_addcurrentdirinsearch.setGeometry(QtCore.QRect(10, 5, 274, 22))
        self.__O_addcurrentdirinsearch.setObjectName("__O_addcurrentdirinsearch")
        self.__O_addrootdirinsearch = QtGui.QCheckBox(self.tab_2)
        self.__O_addrootdirinsearch.setGeometry(QtCore.QRect(10, 25, 311, 22))
        self.__O_addrootdirinsearch.setObjectName("__O_addrootdirinsearch")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 45, 546, 236))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(5, 160, 147, 51))
        self.label_24.setObjectName("label_24")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(5, 85, 147, 51))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(5, 30, 147, 27))
        self.label_8.setObjectName("label_8")
        self.__O_grammarsearchpathlist = QtGui.QPlainTextEdit(self.groupBox_2)
        self.__O_grammarsearchpathlist.setGeometry(QtCore.QRect(80, 160, 456, 66))
        self.__O_grammarsearchpathlist.setObjectName("__O_grammarsearchpathlist")
        self.__O_profilesearchpathlist = QtGui.QPlainTextEdit(self.groupBox_2)
        self.__O_profilesearchpathlist.setGeometry(QtCore.QRect(80, 85, 456, 66))
        self.__O_profilesearchpathlist.setObjectName("__O_profilesearchpathlist")
        self.__O_linksearchpathlist = QtGui.QPlainTextEdit(self.groupBox_2)
        self.__O_linksearchpathlist.setGeometry(QtCore.QRect(80, 15, 456, 61))
        self.__O_linksearchpathlist.setObjectName("__O_linksearchpathlist")
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(365, 15, 181, 26))
        self.pushButton.setObjectName("pushButton")
        self.tabs.addTab(self.tab_2, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.__O_checkonthefly = QtGui.QCheckBox(self.tab_6)
        self.__O_checkonthefly.setEnabled(False)
        self.__O_checkonthefly.setGeometry(QtCore.QRect(10, 10, 274, 22))
        self.__O_checkonthefly.setCheckable(True)
        self.__O_checkonthefly.setObjectName("__O_checkonthefly")
        self.__O_forcesidslegacymapping = QtGui.QCheckBox(self.tab_6)
        self.__O_forcesidslegacymapping.setEnabled(False)
        self.__O_forcesidslegacymapping.setGeometry(QtCore.QRect(10, 30, 274, 22))
        self.__O_forcesidslegacymapping.setObjectName("__O_forcesidslegacymapping")
        self.__O_forcefortranflag = QtGui.QCheckBox(self.tab_6)
        self.__O_forcefortranflag.setEnabled(False)
        self.__O_forcefortranflag.setGeometry(QtCore.QRect(10, 50, 274, 22))
        self.__O_forcefortranflag.setObjectName("__O_forcefortranflag")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 75, 546, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.__O_valkeylist = QtGui.QPlainTextEdit(self.groupBox_3)
        self.__O_valkeylist.setGeometry(QtCore.QRect(380, 35, 156, 156))
        self.__O_valkeylist.setObjectName("__O_valkeylist")
        self.label_25 = QtGui.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(380, 15, 111, 16))
        self.label_25.setObjectName("label_25")
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(10, 25, 271, 21))
        self.label_31.setObjectName("label_31")
        self.cRecurseGrammarSearch = QtGui.QCheckBox(self.groupBox_3)
        self.cRecurseGrammarSearch.setEnabled(False)
        self.cRecurseGrammarSearch.setGeometry(QtCore.QRect(10, 50, 301, 21))
        self.cRecurseGrammarSearch.setCheckable(False)
        self.cRecurseGrammarSearch.setObjectName("cRecurseGrammarSearch")
        self.tabs.addTab(self.tab_6, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.__O_label_size = QtGui.QSpinBox(self.tab_3)
        self.__O_label_size.setGeometry(QtCore.QRect(395, 20, 46, 27))
        self.__O_label_size.setMinimum(6)
        self.__O_label_size.setMaximum(18)
        self.__O_label_size.setProperty("value", 10)
        self.__O_label_size.setObjectName("__O_label_size")
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 25, 166, 17))
        self.label.setObjectName("label")
        self.__O_label_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_label_bold.setGeometry(QtCore.QRect(455, 25, 86, 21))
        self.__O_label_bold.setText("")
        self.__O_label_bold.setObjectName("__O_label_bold")
        self.__O_label_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_label_italic.setGeometry(QtCore.QRect(500, 25, 86, 21))
        self.__O_label_italic.setText("")
        self.__O_label_italic.setObjectName("__O_label_italic")
        self.__O_label_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_label_family.setGeometry(QtCore.QRect(180, 20, 216, 26))
        self.__O_label_family.setObjectName("__O_label_family")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 55, 161, 17))
        self.label_3.setObjectName("label_3")
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(10, 85, 161, 17))
        self.label_12.setObjectName("label_12")
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(10, 115, 161, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(10, 145, 166, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(10, 175, 166, 17))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(445, 5, 58, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(495, 5, 58, 16))
        self.label_30.setObjectName("label_30")
        self.__O_button_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_button_family.setGeometry(QtCore.QRect(180, 50, 216, 26))
        self.__O_button_family.setObjectName("__O_button_family")
        self.__O_edit_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_edit_family.setGeometry(QtCore.QRect(180, 80, 216, 26))
        self.__O_edit_family.setObjectName("__O_edit_family")
        self.__O_table_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_table_family.setGeometry(QtCore.QRect(180, 110, 216, 26))
        self.__O_table_family.setObjectName("__O_table_family")
        self.__O_nname_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_nname_family.setEnabled(False)
        self.__O_nname_family.setGeometry(QtCore.QRect(180, 140, 216, 26))
        self.__O_nname_family.setObjectName("__O_nname_family")
        self.__O_rname_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_rname_family.setGeometry(QtCore.QRect(180, 170, 216, 26))
        self.__O_rname_family.setObjectName("__O_rname_family")
        self.__O_button_size = QtGui.QSpinBox(self.tab_3)
        self.__O_button_size.setGeometry(QtCore.QRect(395, 50, 46, 27))
        self.__O_button_size.setMinimum(6)
        self.__O_button_size.setMaximum(18)
        self.__O_button_size.setProperty("value", 10)
        self.__O_button_size.setObjectName("__O_button_size")
        self.__O_edit_size = QtGui.QSpinBox(self.tab_3)
        self.__O_edit_size.setGeometry(QtCore.QRect(395, 80, 46, 27))
        self.__O_edit_size.setMinimum(6)
        self.__O_edit_size.setMaximum(18)
        self.__O_edit_size.setProperty("value", 10)
        self.__O_edit_size.setObjectName("__O_edit_size")
        self.__O_table_size = QtGui.QSpinBox(self.tab_3)
        self.__O_table_size.setGeometry(QtCore.QRect(395, 110, 46, 27))
        self.__O_table_size.setMinimum(6)
        self.__O_table_size.setMaximum(18)
        self.__O_table_size.setProperty("value", 10)
        self.__O_table_size.setObjectName("__O_table_size")
        self.__O_nname_size = QtGui.QSpinBox(self.tab_3)
        self.__O_nname_size.setEnabled(False)
        self.__O_nname_size.setGeometry(QtCore.QRect(395, 140, 46, 27))
        self.__O_nname_size.setMinimum(6)
        self.__O_nname_size.setMaximum(18)
        self.__O_nname_size.setProperty("value", 10)
        self.__O_nname_size.setObjectName("__O_nname_size")
        self.__O_rname_size = QtGui.QSpinBox(self.tab_3)
        self.__O_rname_size.setGeometry(QtCore.QRect(395, 170, 46, 27))
        self.__O_rname_size.setMinimum(6)
        self.__O_rname_size.setMaximum(18)
        self.__O_rname_size.setProperty("value", 10)
        self.__O_rname_size.setObjectName("__O_rname_size")
        self.__O_button_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_button_bold.setGeometry(QtCore.QRect(455, 55, 86, 21))
        self.__O_button_bold.setText("")
        self.__O_button_bold.setObjectName("__O_button_bold")
        self.__O_edit_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_edit_bold.setGeometry(QtCore.QRect(455, 85, 86, 21))
        self.__O_edit_bold.setText("")
        self.__O_edit_bold.setObjectName("__O_edit_bold")
        self.__O_table_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_table_bold.setGeometry(QtCore.QRect(455, 115, 86, 21))
        self.__O_table_bold.setText("")
        self.__O_table_bold.setObjectName("__O_table_bold")
        self.__O_nname_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_nname_bold.setEnabled(False)
        self.__O_nname_bold.setGeometry(QtCore.QRect(455, 145, 86, 21))
        self.__O_nname_bold.setText("")
        self.__O_nname_bold.setObjectName("__O_nname_bold")
        self.__O_rname_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_rname_bold.setGeometry(QtCore.QRect(455, 175, 86, 21))
        self.__O_rname_bold.setText("")
        self.__O_rname_bold.setObjectName("__O_rname_bold")
        self.__O_button_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_button_italic.setGeometry(QtCore.QRect(500, 55, 86, 21))
        self.__O_button_italic.setText("")
        self.__O_button_italic.setObjectName("__O_button_italic")
        self.__O_edit_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_edit_italic.setGeometry(QtCore.QRect(500, 85, 86, 21))
        self.__O_edit_italic.setText("")
        self.__O_edit_italic.setObjectName("__O_edit_italic")
        self.__O_table_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_table_italic.setGeometry(QtCore.QRect(500, 115, 86, 21))
        self.__O_table_italic.setText("")
        self.__O_table_italic.setObjectName("__O_table_italic")
        self.__O_nname_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_nname_italic.setEnabled(False)
        self.__O_nname_italic.setGeometry(QtCore.QRect(500, 145, 86, 21))
        self.__O_nname_italic.setText("")
        self.__O_nname_italic.setObjectName("__O_nname_italic")
        self.__O_rname_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_rname_italic.setGeometry(QtCore.QRect(500, 175, 86, 21))
        self.__O_rname_italic.setText("")
        self.__O_rname_italic.setObjectName("__O_rname_italic")
        self.bResetFonts = QtGui.QPushButton(self.tab_3)
        self.bResetFonts.setGeometry(QtCore.QRect(10, 215, 166, 26))
        self.bResetFonts.setObjectName("bResetFonts")
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.__O_showtableindex = QtGui.QCheckBox(self.tab_4)
        self.__O_showtableindex.setGeometry(QtCore.QRect(10, 40, 274, 22))
        self.__O_showtableindex.setObjectName("__O_showtableindex")
        self.__O_oneviewpertreenode = QtGui.QCheckBox(self.tab_4)
        self.__O_oneviewpertreenode.setGeometry(QtCore.QRect(320, 0, 274, 22))
        self.__O_oneviewpertreenode.setObjectName("__O_oneviewpertreenode")
        self.__O_showcolumnindex = QtGui.QCheckBox(self.tab_4)
        self.__O_showcolumnindex.setGeometry(QtCore.QRect(10, 60, 274, 22))
        self.__O_showcolumnindex.setObjectName("__O_showcolumnindex")
        self.__O_showhelpballoons = QtGui.QCheckBox(self.tab_4)
        self.__O_showhelpballoons.setGeometry(QtCore.QRect(10, 80, 274, 22))
        self.__O_showhelpballoons.setObjectName("__O_showhelpballoons")
        self.__O_show1dasplain = QtGui.QCheckBox(self.tab_4)
        self.__O_show1dasplain.setGeometry(QtCore.QRect(10, 20, 274, 22))
        self.__O_show1dasplain.setObjectName("__O_show1dasplain")
        self.__O_showsidsstatuscolumn = QtGui.QCheckBox(self.tab_4)
        self.__O_showsidsstatuscolumn.setGeometry(QtCore.QRect(10, 0, 274, 22))
        self.__O_showsidsstatuscolumn.setObjectName("__O_showsidsstatuscolumn")
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 217, 27))
        self.label_2.setObjectName("label_2")
        self.__O_maxlengthdatadisplay = QtGui.QSpinBox(self.tab_4)
        self.__O_maxlengthdatadisplay.setGeometry(QtCore.QRect(230, 110, 101, 27))
        self.__O_maxlengthdatadisplay.setMinimum(1)
        self.__O_maxlengthdatadisplay.setMaximum(999999999)
        self.__O_maxlengthdatadisplay.setSingleStep(10)
        self.__O_maxlengthdatadisplay.setProperty("value", 700)
        self.__O_maxlengthdatadisplay.setObjectName("__O_maxlengthdatadisplay")
        self.__O_transposearrayforview = QtGui.QCheckBox(self.tab_4)
        self.__O_transposearrayforview.setGeometry(QtCore.QRect(320, 20, 274, 22))
        self.__O_transposearrayforview.setObjectName("__O_transposearrayforview")
        self.__O_autoexpand = QtGui.QCheckBox(self.tab_4)
        self.__O_autoexpand.setGeometry(QtCore.QRect(320, 50, 166, 21))
        self.__O_autoexpand.setObjectName("__O_autoexpand")
        self.tabs.addTab(self.tab_4, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(5, 0, 191, 281))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_8 = QtGui.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(35, 150, 41, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_15 = QtGui.QComboBox(self.groupBox)
        self.comboBox_15.setGeometry(QtCore.QRect(85, 75, 96, 22))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_19 = QtGui.QComboBox(self.groupBox)
        self.comboBox_19.setGeometry(QtCore.QRect(85, 250, 96, 22))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(35, 50, 41, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_14 = QtGui.QComboBox(self.groupBox)
        self.comboBox_14.setGeometry(QtCore.QRect(85, 100, 96, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_16 = QtGui.QComboBox(self.groupBox)
        self.comboBox_16.setGeometry(QtCore.QRect(85, 175, 96, 22))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_17 = QtGui.QComboBox(self.groupBox)
        self.comboBox_17.setGeometry(QtCore.QRect(85, 125, 96, 22))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_10 = QtGui.QComboBox(self.groupBox)
        self.comboBox_10.setGeometry(QtCore.QRect(35, 225, 41, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_20 = QtGui.QComboBox(self.groupBox)
        self.comboBox_20.setGeometry(QtCore.QRect(85, 225, 96, 22))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(35, 25, 41, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_9 = QtGui.QComboBox(self.groupBox)
        self.comboBox_9.setGeometry(QtCore.QRect(85, 200, 96, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(35, 75, 41, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_11 = QtGui.QComboBox(self.groupBox)
        self.comboBox_11.setGeometry(QtCore.QRect(35, 250, 41, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_6 = QtGui.QComboBox(self.groupBox)
        self.comboBox_6.setGeometry(QtCore.QRect(35, 200, 41, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_18 = QtGui.QComboBox(self.groupBox)
        self.comboBox_18.setGeometry(QtCore.QRect(85, 25, 96, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_4 = QtGui.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(35, 100, 41, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_7 = QtGui.QComboBox(self.groupBox)
        self.comboBox_7.setGeometry(QtCore.QRect(35, 175, 41, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_5 = QtGui.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(35, 125, 41, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_13 = QtGui.QComboBox(self.groupBox)
        self.comboBox_13.setGeometry(QtCore.QRect(85, 150, 96, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_12 = QtGui.QComboBox(self.groupBox)
        self.comboBox_12.setGeometry(QtCore.QRect(85, 50, 96, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(15, 250, 58, 16))
        self.label_22.setObjectName("label_22")
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(15, 75, 58, 16))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(15, 175, 58, 16))
        self.label_19.setObjectName("label_19")
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(15, 25, 58, 16))
        self.label_13.setObjectName("label_13")
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(15, 200, 58, 16))
        self.label_20.setObjectName("label_20")
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(15, 150, 58, 16))
        self.label_18.setObjectName("label_18")
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(15, 100, 58, 16))
        self.label_16.setObjectName("label_16")
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(15, 50, 58, 16))
        self.label_14.setObjectName("label_14")
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(15, 125, 58, 16))
        self.label_17.setObjectName("label_17")
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(15, 225, 58, 16))
        self.label_21.setObjectName("label_21")
        self.tabs.addTab(self.tab, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_4 = QtGui.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 15, 147, 27))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 45, 147, 27))
        self.label_5.setObjectName("label_5")
        self.__O_snapshotdirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_snapshotdirectory.setGeometry(QtCore.QRect(160, 45, 391, 27))
        self.__O_snapshotdirectory.setObjectName("__O_snapshotdirectory")
        self.__O_queriesdirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_queriesdirectory.setGeometry(QtCore.QRect(160, 15, 391, 27))
        self.__O_queriesdirectory.setObjectName("__O_queriesdirectory")
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 75, 147, 27))
        self.label_6.setObjectName("label_6")
        self.__O_selectionlistdirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_selectionlistdirectory.setGeometry(QtCore.QRect(160, 75, 391, 27))
        self.__O_selectionlistdirectory.setObjectName("__O_selectionlistdirectory")
        self.__O_chlonetrace = QtGui.QCheckBox(self.tab_5)
        self.__O_chlonetrace.setGeometry(QtCore.QRect(10, 215, 111, 21))
        self.__O_chlonetrace.setObjectName("__O_chlonetrace")
        self.__O_navtrace = QtGui.QCheckBox(self.tab_5)
        self.__O_navtrace.setGeometry(QtCore.QRect(10, 195, 131, 21))
        self.__O_navtrace.setObjectName("__O_navtrace")
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(10, 115, 147, 27))
        self.label_10.setObjectName("label_10")
        self.__O_adfconversioncom = QtGui.QLineEdit(self.tab_5)
        self.__O_adfconversioncom.setGeometry(QtCore.QRect(160, 115, 391, 27))
        self.__O_adfconversioncom.setObjectName("__O_adfconversioncom")
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(10, 145, 151, 27))
        self.label_11.setObjectName("label_11")
        self.__O_temporarydirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_temporarydirectory.setGeometry(QtCore.QRect(160, 145, 391, 27))
        self.__O_temporarydirectory.setObjectName("__O_temporarydirectory")
        self.line_2 = QtGui.QFrame(self.tab_5)
        self.line_2.setGeometry(QtCore.QRect(10, 180, 536, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.__O_activatemultithreading = QtGui.QCheckBox(self.tab_5)
        self.__O_activatemultithreading.setGeometry(QtCore.QRect(375, 195, 166, 21))
        self.__O_activatemultithreading.setObjectName("__O_activatemultithreading")
        self.tabs.addTab(self.tab_5, "")
        self.horizontalLayout_2.addWidget(self.tabs)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bReset = QtGui.QPushButton(Q7OptionsWindow)
        self.bReset.setObjectName("bReset")
        self.horizontalLayout.addWidget(self.bReset)
        self.bInfo = QtGui.QPushButton(Q7OptionsWindow)
        self.bInfo.setMinimumSize(QtCore.QSize(25, 25))
        self.bInfo.setMaximumSize(QtCore.QSize(25, 25))
        self.bInfo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/help-view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInfo.setIcon(icon1)
        self.bInfo.setObjectName("bInfo")
        self.horizontalLayout.addWidget(self.bInfo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bApply = QtGui.QPushButton(Q7OptionsWindow)
        self.bApply.setObjectName("bApply")
        self.horizontalLayout.addWidget(self.bApply)
        self.bClose = QtGui.QPushButton(Q7OptionsWindow)
        self.bClose.setObjectName("bClose")
        self.horizontalLayout.addWidget(self.bClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Q7OptionsWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Q7OptionsWindow)

    def retranslateUi(self, Q7OptionsWindow):
        Q7OptionsWindow.setWindowTitle(QtGui.QApplication.translate("Q7OptionsWindow", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_recursivetreedisplay.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Recursive tree display", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_recursivesidspatternsload.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Recursive SIDS patterns load", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_donotdisplaylargedata.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Do not dispay large data", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_followlinksatload.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Follow links during file load", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_donotfollowlinksatsave.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Do not follow links during file save", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_donotloadlargearrays.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Do not load large data arrays", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Max tree parse recursion level", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_stoploadbrokenlinks.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Stop loading on broken link", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_filterhdffiles.setText(QtGui.QApplication.translate("Q7OptionsWindow", "filter *.hdf files", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_filtercgnsfiles.setText(QtGui.QApplication.translate("Q7OptionsWindow", "filter *.cgns files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Display nodes with data size below:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Do not load node data if above:", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_fileupdateremoveschildren.setText(QtGui.QApplication.translate("Q7OptionsWindow", "File update removes missing children", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_1), QtGui.QApplication.translate("Q7OptionsWindow", "Load/Save", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_addcurrentdirinsearch.setToolTip(QtGui.QApplication.translate("Q7OptionsWindow", "Set to always add the current directory as the first in the linked-to files search.", "Set to always add the current directory as the first in the linked-to files search.", QtGui.QApplication.UnicodeUTF8))
        self.__O_addcurrentdirinsearch.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Add current dir in link search path", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_addrootdirinsearch.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Add file system root dir in link search path", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Q7OptionsWindow", "Search paths", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Grammars", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Links", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Remove unreachable paths", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), QtGui.QApplication.translate("Q7OptionsWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_checkonthefly.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Check on the fly", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_forcesidslegacymapping.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Force SIDS legacy mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_forcefortranflag.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Force fortran flag in numpy arrays", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Q7OptionsWindow", "CGNS.VAL parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Grammar keys", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Q7OptionsWindow", "See also: Paths tab and grammars paths", None, QtGui.QApplication.UnicodeUTF8))
        self.cRecurseGrammarSearch.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Activate recursion search for grammars (long)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_6), QtGui.QApplication.translate("Q7OptionsWindow", "Checks", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Q7OptionsWindow", "label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Q7OptionsWindow", "button", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Q7OptionsWindow", "text edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Q7OptionsWindow", "table (Form view)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Q7OptionsWindow", "graphic (VTK view)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Q7OptionsWindow", "node name (Tree view)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.bResetFonts.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Reset to default fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QtGui.QApplication.translate("Q7OptionsWindow", "Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_showtableindex.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Show table index", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_oneviewpertreenode.setText(QtGui.QApplication.translate("Q7OptionsWindow", "One view per tree/node", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_showcolumnindex.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Show columns titles", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_showhelpballoons.setToolTip(QtGui.QApplication.translate("Q7OptionsWindow", "Shows the help balloon you are reading right now.", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_showhelpballoons.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Show tooltips", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_show1dasplain.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Show 1D values as Python plain types", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_showsidsstatuscolumn.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Show SIDS status column", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Max length of data display in tree", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_transposearrayforview.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Transpose arrays for view/edit", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_autoexpand.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Auto expand tree view ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), QtGui.QApplication.translate("Q7OptionsWindow", "Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Q7OptionsWindow", "Colors/Icons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Q7OptionsWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Q7OptionsWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Q7OptionsWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Q7OptionsWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Q7OptionsWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Q7OptionsWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Q7OptionsWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Q7OptionsWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Q7OptionsWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Q7OptionsWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), QtGui.QApplication.translate("Q7OptionsWindow", "User flags", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Q7OptionsWindow", "User queries directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Snapshot directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Selection list directory", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_chlonetrace.setText(QtGui.QApplication.translate("Q7OptionsWindow", "CHLone trace", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_navtrace.setText(QtGui.QApplication.translate("Q7OptionsWindow", "CGNS.NAV trace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Q7OptionsWindow", "ADF conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Temporary directory", None, QtGui.QApplication.UnicodeUTF8))
        self.__O_activatemultithreading.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Activate Multi-threading", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), QtGui.QApplication.translate("Q7OptionsWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.bReset.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.bApply.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.bClose.setText(QtGui.QApplication.translate("Q7OptionsWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

import Res_rc
