# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGNS/NAV/T/Q7ToolsWindow.ui'
#
# Created: Tue Jan  8 16:11:19 2013
#      by: pyside-uic 0.2.13 running on PySide 1.0.9
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Q7ToolsWindow(object):
    def setupUi(self, Q7ToolsWindow):
        Q7ToolsWindow.setObjectName("Q7ToolsWindow")
        Q7ToolsWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Q7ToolsWindow.resize(580, 364)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7ToolsWindow.sizePolicy().hasHeightForWidth())
        Q7ToolsWindow.setSizePolicy(sizePolicy)
        Q7ToolsWindow.setMinimumSize(QtCore.QSize(580, 364))
        Q7ToolsWindow.setMaximumSize(QtCore.QSize(580, 364))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/cgSpy.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7ToolsWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Q7ToolsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Q7ToolsWindow)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.diff = QtGui.QWidget()
        self.diff.setObjectName("diff")
        self.gdiff = QtGui.QGroupBox(self.diff)
        self.gdiff.setGeometry(QtCore.QRect(5, 5, 541, 266))
        self.gdiff.setObjectName("gdiff")
        self.label = QtGui.QLabel(self.gdiff)
        self.label.setGeometry(QtCore.QRect(25, 25, 58, 16))
        self.label.setObjectName("label")
        self.cAncestor = QtGui.QComboBox(self.gdiff)
        self.cAncestor.setGeometry(QtCore.QRect(15, 45, 81, 22))
        self.cAncestor.setObjectName("cAncestor")
        self.cVersionA = QtGui.QComboBox(self.gdiff)
        self.cVersionA.setGeometry(QtCore.QRect(140, 45, 81, 22))
        self.cVersionA.setObjectName("cVersionA")
        self.label_2 = QtGui.QLabel(self.gdiff)
        self.label_2.setGeometry(QtCore.QRect(150, 25, 58, 16))
        self.label_2.setObjectName("label_2")
        self.cShowA = QtGui.QCheckBox(self.gdiff)
        self.cShowA.setEnabled(False)
        self.cShowA.setGeometry(QtCore.QRect(235, 45, 176, 21))
        self.cShowA.setCheckable(True)
        self.cShowA.setChecked(False)
        self.cShowA.setObjectName("cShowA")
        self.bDiff = QtGui.QPushButton(self.gdiff)
        self.bDiff.setGeometry(QtCore.QRect(395, 45, 25, 25))
        self.bDiff.setMinimumSize(QtCore.QSize(25, 25))
        self.bDiff.setMaximumSize(QtCore.QSize(25, 25))
        self.bDiff.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/operate-execute.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDiff.setIcon(icon1)
        self.bDiff.setObjectName("bDiff")
        self.tabWidget.addTab(self.diff, "")
        self.split = QtGui.QWidget()
        self.split.setObjectName("split")
        self.tabWidget.addTab(self.split, "")
        self.merge = QtGui.QWidget()
        self.merge.setObjectName("merge")
        self.tabWidget.addTab(self.merge, "")
        self.process = QtGui.QWidget()
        self.process.setObjectName("process")
        self.tabWidget.addTab(self.process, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bInfo = QtGui.QPushButton(Q7ToolsWindow)
        self.bInfo.setMinimumSize(QtCore.QSize(25, 25))
        self.bInfo.setMaximumSize(QtCore.QSize(25, 25))
        self.bInfo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/help-view.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInfo.setIcon(icon2)
        self.bInfo.setObjectName("bInfo")
        self.horizontalLayout.addWidget(self.bInfo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bClose = QtGui.QPushButton(Q7ToolsWindow)
        self.bClose.setObjectName("bClose")
        self.horizontalLayout.addWidget(self.bClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Q7ToolsWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Q7ToolsWindow)

    def retranslateUi(self, Q7ToolsWindow):
        Q7ToolsWindow.setWindowTitle(QtGui.QApplication.translate("Q7ToolsWindow", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.gdiff.setTitle(QtGui.QApplication.translate("Q7ToolsWindow", "All tree identifications use view number", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Q7ToolsWindow", "Version A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Q7ToolsWindow", "Version B", None, QtGui.QApplication.UnicodeUTF8))
        self.cShowA.setText(QtGui.QApplication.translate("Q7ToolsWindow", "Show result on B view", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diff), QtGui.QApplication.translate("Q7ToolsWindow", "Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.split), QtGui.QApplication.translate("Q7ToolsWindow", "Split", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.merge), QtGui.QApplication.translate("Q7ToolsWindow", "Merge", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.process), QtGui.QApplication.translate("Q7ToolsWindow", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.bClose.setText(QtGui.QApplication.translate("Q7ToolsWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))

import Res_rc
