isOff="""R0lGODlhCQAQAJH/AMDAwAAAAGnD/wAAACH5BAEAAAAALAAA
AAAJABAAQAIdhI8hu2EqXIroyQrb\nyRf0VG0UxnSZ5jFjulrhaxQAO6olVwAAOw=="""

isOn="""R0lGODlhEAAJAJH/AMDAwAAAAGnD/wAAACH5BAEAAAAALAAA
AAAQAAkAQAIahI+pyyEPg3KwPrko\nTqH7/yGUJWxcZTapUQAAO8byUgAAOw=="""

attribute="""
R0lGODlhEAAQAIAAABwt/////yH5BAEKAAEALAAAAAAQABAAAAIbjI8JybjdHlSTyWou1pVPD4ER
5pCHaJmZGgAFADs=
"""

comment="""R0lGODlhCwAOAJEAAAAAAICAgP///8DAwCH5BAEAAAMALAAA
AAALAA4AAAIphA+jA+JuVgtUtMQePJlWCgSN9oSTV5lkKQpo2q5W+
wbzuJrIHgw1WgAAOw=="""

# --- original icons from Tree.py (Charles E. "Gene" Cash)

expanded_original="""R0lGODlhEAANAKIAAAAAAMDAwICAgP//////ADAwMAAAAAAA
ACH5BAEAAAEALAAAAAAQAA0AAAM6GCrM+jCIQamIbw6ybXNSx3GVB
YRiygnA534Eq5UlO8jUqLYsquuy0+SXap1CxBHr+HoBjoGndDpNAAA7"""

collapsed_original="""R0lGODlhDwANAKIAAAAAAMDAwICAgP//////ADAwMAAAAAAA
ACH5BAEAAAEALAAAAAAPAA0AAAMyGCHM+lAMMoeAT9Jtm5NDKI4Wo
FXcJphhipanq7Kvu8b1dLc5tcuom2foAQQAyKRSmQAAOw=="""

regular_original="""R0lGODlhCwAOAJEAAAAAAICAgP///8DAwCH5BAEAAAMALAAA
AAALAA4AAAIphA+jA+JuVgtUtMQePJlWCgSN9oSTV5lkKQpo2q5W+
wbzuJrIHgw1WgAAOw=="""

plus_original="""R0lGODdhCQAJAPEAAAAAAH9/f////wAAACwAAAAACQAJAAAC
FIyPoiu2sJyCyoF7W3hxz850CFIA\nADs="""

minus_original="""R0lGODdhCQAJAPEAAAAAAH9/f////wAAACwAAAAACQAJAAAC
EYyPoivG614LAlg7ZZbxoR8UADs="""

# ---
