#!/usr/bin/env python
# ------------------------------------------------------------
# pyDAX - Tools - daxET
# ------------------------------------------------------------
# $Id: daxET 35 2003-08-22 15:21:06Z mpoinot $
#
import DAX.db.connect as dx
import DAX.exceptions as ex
import DAX.utils      as ut
#
import getopt
daxEToptionError="daxEToptionError"
# ------------------------------------------------------------
def parseAndRun(args):
  opt,arg=getopt.getopt(args,"tTx:e:i:p:u")
  connection = None
  command    = None
  baseid     = None
  path       = None
  compress   = 1
  for o,v in opt:
    if (o == "-T"):
      ut.DAXtraceFlag=2
    if (o == "-t"):
      ut.DAXtraceFlag=1
    if (o == "-x"):
      connection=tuple(v.split(":"))
    if (o == "-u"):
      if (not connection): raise daxEToptionError
      if (not command):    raise daxEToptionError
      if (not path):       raise daxEToptionError      
      compress=0
    if (o in ["-e","-i"]):
      if (not connection): raise daxEToptionError
      if (command):        raise daxEToptionError
      command=o
      baseid =v
    if (o == "-p"):
      if (not connection): raise daxEToptionError
      if (not command):    raise daxEToptionError
      if (path):           raise daxEToptionError      
      path=v
  if (   (not command)
      or (not connection)
      or (not baseid)): raise daxEToptionError
  # ----------    
  if (command == "-e"):
    d=dx.daxET(connection)
    d.exportTree(baseid,path,compress=compress)
    del d
  # ----------    
  if (command == "-i"):
    d=dx.daxET(connection)
    d.importTree(baseid,path)
    del d
    
# ------------------------------------------------------------
def usage():
    print """\
daxET   : DAX export tool
usage   : daxET -x <database-connection> [command and option]
        : commands are exclusives, options should be ordered
        : <database-connection> is <databasename>:<username>:<password>
        : Do NOT compress at export time with option -u
        : Uncompress is done if the target file ends with .gz
        : File complete name is <file-identifier>.dax.tar.gz
        : -t option give a short trace, -T gives verbose trace
commands:
 -e export   = [-t|-T] -e <file-identifier> -p <unix-file-path> [-u]
 -i import   = [-t|-T] -i <file-identifier> -p <unix-file-path> 
"""
if (__name__ == "__main__"):
  import sys
  try:
    parseAndRun(sys.argv[1:])
  except daxEToptionError:   usage()
#  except IndexError:         usage()
  except getopt.GetoptError: usage()

  # DAX exceptions
  except ex.DAXException, e: print e

    
