#  -------------------------------------------------------------------------
#  pyCGNS - Python package for CFD General Notation System -
#  See license.txt file in the root directory of this Python module source  
#  -------------------------------------------------------------------------
#
# now all the code is in CHLone and its CGNS/Python interface
#
from CHLone import load
from CHLone import save
from CHLone import probe
from CHLone import CHLoneException as error
#
import CHLone

S2P_NONE=CHLone.FNONE
S2P_ALL=CHLone.FALL
S2P_TRACE=CHLone.FTRACE
S2P_FOLLOWLINKS=CHLone.FFOLLOWLINKS
S2P_DEBUG=CHLone.FDEBUG
S2P_NODATA=CHLone.FNODATA
S2P_MERGELINKS=0
S2P_COMPRESS=CHLone.FCOMPRESS
S2P_REVERSEDIMS=CHLone.FREVERSEDIMS
S2P_OWNDATA=CHLone.FOWNDATA
S2P_UPDATE=CHLone.FUPDATE
S2P_DELETEMISSING=CHLone.FDELETEMISSING
S2P_ALTERNATESIDS=CHLone.FALTERNATESIDS
S2P_NOTRANSPOSE=0
S2P_UPDATEONLY=CHLone.FUPDATEONLY
S2P_FORTRANFLAG=CHLone.FFORTRANFLAG
S2P_PROPAGATE=CHLone.FPROPAGATE
S2P_NOI8=CHLone.FNOI8
S2P_DEFAULT=CHLone.FDEFAULT
S2P_DEFAULTS=CHLone.FDEFAULTS
S2P_KEEPLIST=CHLone.FKEEPLIST

S2P_LKOK=CHLone.LKOK
S2P_LKFAIL=CHLone.LKFAIL
S2P_LKBADSYNTAX=CHLone.LKBADSYNTAX
S2P_LKNOFILE=CHLone.LKNOFILE
S2P_LKFILENOREAD=CHLone.LKFILENOREAD
S2P_LKNONODE=CHLone.LKNONODE
S2P_LKLOOP=CHLone.LKLOOP
S2P_LKIGNORED=CHLone.LKIGNORED

NONE=CHLone.FNONE
ALL=CHLone.FALL
TRACE=CHLone.FTRACE
FOLLOWLINKS=CHLone.FFOLLOWLINKS
DEBUG=CHLone.FDEBUG
NODATA=CHLone.FNODATA
MERGELINKS=0
COMPRESS=CHLone.FCOMPRESS
REVERSEDIMS=CHLone.FREVERSEDIMS
OWNDATA=CHLone.FOWNDATA
UPDATE=CHLone.FUPDATE
DELETEMISSING=CHLone.FDELETEMISSING
ALTERNATESIDS=CHLone.FALTERNATESIDS
NOTRANSPOSE=0
UPDATEONLY=CHLone.FUPDATEONLY
FORTRANFLAG=CHLone.FFORTRANFLAG
PROPAGATE=CHLone.FPROPAGATE
NOI8=CHLone.FNOI8
DEFAULT=CHLone.FDEFAULT
DEFAULTS=CHLone.FDEFAULTS
KEEPLIST=CHLone.FKEEPLIST

LKOK=CHLone.LKOK
LKFAIL=CHLone.LKFAIL
LKBADSYNTAX=CHLone.LKBADSYNTAX
LKNOFILE=CHLone.LKNOFILE
LKFILENOREAD=CHLone.LKFILENOREAD
LKNONODE=CHLone.LKNONODE
LKLOOP=CHLone.LKLOOP
LKIGNORED=CHLone.LKIGNORED

# --- last line
