#  -------------------------------------------------------------------------
#  pyCGNS.VAL - Python package for CFD General Notation System - VALidater
#  See license.txt file in the root directory of this Python module source  
#  -------------------------------------------------------------------------
#
import CGNS.VAL.parse.messages as CGM

messagetable=(
('S101',CGM.CHECK_FAIL,'Unknown ZoneType value'),
('S102',CGM.CHECK_FAIL,'Unknown SimulationType value'),
('S103',CGM.CHECK_FAIL,'Unknown GridLocation value'),
('S104',CGM.CHECK_FAIL,'Unknown GridConnectivityType value'),
('S105',CGM.CHECK_FAIL,'Unknown DataClass value'),
('S106',CGM.CHECK_FAIL,'Unknown BCDataType value'),
('S107',CGM.CHECK_FAIL,'Unknown RigidMotionType value'),
('S108',CGM.CHECK_FAIL,'Unknown BCType value'),
('S109',CGM.CHECK_FAIL,'Unknown ElementType value'),
('S110',CGM.CHECK_FAIL,'Unknown MassUnit value'),
('S111',CGM.CHECK_FAIL,'Unknown LengthUnit value'),
('S112',CGM.CHECK_FAIL,'Unknown TimeUnit value'),
('S113',CGM.CHECK_FAIL,'Unknown TemperatureUnit value'),
('S114',CGM.CHECK_FAIL,'Unknown AngleUnit value'),
('S115',CGM.CHECK_FAIL,'Unknown ElectricCurrentUnit value'),
('S116',CGM.CHECK_FAIL,'Unknown SubstanceAmountUnit value'),
('S117',CGM.CHECK_FAIL,'Unknown LuminousIntensityUnit value'),
('S118',CGM.CHECK_FAIL,'Unknown ArbitraryMotionType value'),
('S119',CGM.CHECK_FAIL,'Unknown PointSetType value'),
('S120',CGM.CHECK_FAIL,'Name [%s] is reserved for a child of type [%s]'),
('S121',CGM.CHECK_WARN,'Name [%s] is not known as a CGNS/SIDS identifier'),
('S122',CGM.CHECK_FAIL,'Name [%s] is not authorized for a node of type [%s], should be in list [%s]'),
('S123',CGM.CHECK_WARN,'Default [%s] is set to [%s]'),

('S150',CGM.CHECK_WARN,'No default DataClass set'),
('S151',CGM.CHECK_WARN,'Default GridLocation is set to Vertex'),
('S152',CGM.CHECK_WARN,'Default GridConnectivityType is set to Overset'),
('S153',CGM.CHECK_WARN,'DataClass defined without DimensionalUnits'),
('S154',CGM.CHECK_WARN,'Local DataClass refers to a parent DimensionalUnits'),
('S155',CGM.CHECK_WARN,'DataArray refers to a parent DataClass'),
('S156',CGM.CHECK_FAIL,'DimensionalExponents without DataClass'),
('S157',CGM.CHECK_FAIL,'DimensionalExponents without DimensionalUnits'),
('S158',CGM.CHECK_WARN,'DataConversion without DataClass'),
('S159',CGM.CHECK_WARN,'DataConversion without DimensionalUnits'),
('S160',CGM.CHECK_WARN,'DataConversion without DimensionalExponents'),
('S161',CGM.CHECK_FAIL,'DataClass requires DimensionalUnits'),
('S162',CGM.CHECK_WARN,'DataClass does not require DimensionalUnits'),
('S163',CGM.CHECK_WARN,'DataClass does not require DimensionalExponents'),
('S164',CGM.CHECK_FAIL,'DimensionalUnits without DataClass'),

('S170',CGM.CHECK_FAIL,'Unknown AverageInterfaceType value'),
('S171',CGM.CHECK_FAIL,'Unknown GeometryFormat value'),
('S172',CGM.CHECK_FAIL,'Unknown GoverningEquationsType value'),
('S173',CGM.CHECK_FAIL,'Unknown ThermalConductivityModelType value'),
('S174',CGM.CHECK_FAIL,'Unknown TurbulenceClosureType value'),
('S175',CGM.CHECK_FAIL,'Unknown ThermalConductivityModelIdentifier value'),
('S176',CGM.CHECK_FAIL,'Unknown TurbulenceClosureIdentifier value'),
('S177',CGM.CHECK_FAIL,'Unknown TurbulenceModelType value'),
('S178',CGM.CHECK_FAIL,'Unknown ViscosityModelType value'),
('S179',CGM.CHECK_FAIL,'Unknown ViscosityModelIdentifier value'),
('S180',CGM.CHECK_FAIL,'Unknown GasModelType value'),
('S181',CGM.CHECK_FAIL,'Unknown GasModelIdentifier value'),
('S182',CGM.CHECK_FAIL,'Unknown ThermalRelaxationModelType value'),
('S183',CGM.CHECK_FAIL,'Unknown ChemicalKineticsModelType value'),
('S184',CGM.CHECK_FAIL,'Unknown ChemicalKineticsModelIdentifier value'),
('S185',CGM.CHECK_FAIL,'Unknown EMElectricFieldModelType value'),
('S186',CGM.CHECK_FAIL,'Unknown EMMagneticFieldModelType value'),
('S187',CGM.CHECK_FAIL,'Unknown EMConductivityModelType value'),
('S188',CGM.CHECK_FAIL,'Unknown EMConductivityModelIdentifier value'),
('S189',CGM.CHECK_FAIL,'Unknown BCTypeSimple value'),
('S190',CGM.CHECK_FAIL,'Unknown BCTypeCompound value'),
('S191',CGM.CHECK_FAIL,'Bad node value shape'),
('S192',CGM.CHECK_FAIL,'Unexpected shape [%s] instead of [%s] for [%s]'),
('S193',CGM.CHECK_FAIL,'Missing required node of type [%s] in [%s]'),
('S194',CGM.CHECK_FAIL,'Missing required node of name [%s]'),
('S195',CGM.CHECK_FAIL,'Bad child node value shape [%s]'),
('S196',CGM.CHECK_FAIL,'Bad child node value datatype [%s]'),
('S197',CGM.CHECK_FAIL,'Inconsistent child node value [%s]'),
('S198',CGM.CHECK_FAIL,'Missing child [%s] in case child [%s] present'),
('S199',CGM.CHECK_FAIL,'DataType [%s] not allowed for this node, expected type among [%s]'),

('S201',CGM.CHECK_FAIL,'Inconsistent PhysicalDimension/CellDimension'),
('S202',CGM.CHECK_FAIL,'Bad value for CellDimension'),
('S203',CGM.CHECK_FAIL,'Bad value for PhysicalDimension'),
('S204',CGM.CHECK_FAIL,'Bad Transform values'),
('S205',CGM.CHECK_FAIL,'Bad ElementSizeBoundary value'),

('S206',CGM.CHECK_FAIL,'Values out of range'),
('S207',CGM.CHECK_WARN,'Values not ordered'),
('S208',CGM.CHECK_WARN,'Values appear several times in list'),

('S209',CGM.CHECK_FAIL,'Bad combination of ElementRange values'),
('S210',CGM.CHECK_WARN,'[%s] suitable for face Elements only'),
('S211',CGM.CHECK_FAIL,'Values out of range for GridLocation [%s], index [%s/%s], accepted range within [%s]'),
('S212',CGM.CHECK_FAIL,'Unvalid element at position [%s] for [%s] face type'),
('S213',CGM.CHECK_FAIL,'Bad [%s] face position [%s] for parent element [%s]'),
('S214',CGM.CHECK_FAIL,'ParentElements child required together with ParentElementsPosition'),
('S215',CGM.CHECK_FAIL,'GridLocation [%s] not valid for CellDimension [%s] and RegionCellDimension [%s]'),
('S216',CGM.CHECK_FAIL,'GridLocation [%s] not valid'),
('S217',CGM.CHECK_FAIL,'Values out of range, index [%s/%s], accepted range within [%s]'),
('S218',CGM.CHECK_FAIL,'GridLocation [%s] not valid for [%s] node, required among [%s]'),
('S219',CGM.CHECK_FAIL,'A face is expected'),
('S220',CGM.CHECK_FAIL,'Prohibited (0,0) adjacent cell couples for face elements [%s]'),

('S221',CGM.CHECK_WARN,'BCType is [%s]'),
('S222',CGM.CHECK_FAIL,'Both PointRange and PointList children is not allowed'),
('S223',CGM.CHECK_FAIL,'PointRange or PointList child is mandatory'),
('S224',CGM.CHECK_FAIL,'One and only one of these children is mandatory: %s'),

('S230',CGM.CHECK_FAIL,'Bad [%s] values, expected [%s]'),

('S260',CGM.CHECK_FAIL,'GridCoordinates node has no coordinate array'),
('S261',CGM.CHECK_FAIL,'Coordinates number different from PhysicalDimension'),
('S262',CGM.CHECK_FAIL,'Size of coordinates different from zone DataSize (VertexSize if no Rind)'),
('S263',CGM.CHECK_FAIL,'Unable to identify coordinate system from names'),
('S264',CGM.CHECK_FAIL,'Coordinate name not allowed for 1D system'),
('S265',CGM.CHECK_FAIL,'Coordinate name not allowed for 2D system'),
('S266',CGM.CHECK_FAIL,'Coordinate name not allowed for 3D system'),

('S270',CGM.CHECK_WARN,'Descriptor contains non-printable or non-ascii chars'),

('S280',CGM.CHECK_FAIL,'DiffusionModel should have a value'),
('S281',CGM.CHECK_FAIL,'DiffusionModel value should have dimension of %d'),
('S282',CGM.CHECK_FAIL,'DiffusionModel value should contain only 0s or 1s'),

('S300',CGM.CHECK_FAIL,'FamilyName is empty'),
('S301',CGM.CHECK_FAIL,'Reference to unknown family [%s]'),
('S302',CGM.CHECK_FAIL,'Reference to unknown additional family [%s]'),
('S303',CGM.CHECK_WARN,'Family is never referenced'),
('S304',CGM.CHECK_FAIL,'FamilyName_t child is mandatory for FamilySpecified BC'),

('S400',CGM.CHECK_FAIL,'Cannot get connectivity donor zone'),
('S401',CGM.CHECK_FAIL,'Connectivity donor zone [%s] not found'),

('S501',CGM.CHECK_FAIL,'Reference to unknown node [%s] in [%s]'),
('S502',CGM.CHECK_FAIL,'Bad iteration number [%s]'),
('S503',CGM.CHECK_FAIL,'Name [%s] is reserved for time-dependant pointers'),
('S504',CGM.CHECK_FAIL,'Name [%s] is reserved for ConvergenceHistory'),

('S600',CGM.CHECK_WARN,'CGNSTree has no CGNSBase'),
('S601',CGM.CHECK_WARN,'CGNSBase has no Zone'),
('S602',CGM.CHECK_FAIL,'Zone has no GridCoordinates'),
('S603',CGM.CHECK_FAIL,'No GridCoordinates_t of name GridCoordinates in zone'),
('S604',CGM.CHECK_WARN,'ZoneBC has no BC'),
('S605',CGM.CHECK_FAIL,'Unstructured zone has no Elements'),
('S606',CGM.CHECK_FAIL,'ElementConnectivity child node absent'),
('S607',CGM.CHECK_FAIL,'ElementRange child node absent'),
('S608',CGM.CHECK_FAIL,'Structured zone should not have Elements'),
('S609',CGM.CHECK_WARN,'ElementRange is reserved for Elements of unstructured zones'),

('S620',CGM.CHECK_FAIL,'GridConnectivity1to1 only applies to structured zones interfacing with structured donors'),
('S621',CGM.CHECK_FAIL,'Opposite GridConnectivity1to1 not found in zone [%s]'),

('S700',CGM.CHECK_WARN,'Faces [%s] defined as boundary regarding [%s] do not belong to any BC or GridConnectivity'),
('S701',CGM.CHECK_WARN,'Faces [%s] defined as boundary regarding [%s] belong to more than one BC and/or GridConnectivity'),
('S702',CGM.CHECK_WARN,'Boundary [%s] face indices [%s] do not belong to any BC or GridConnectivity'),
('S703',CGM.CHECK_WARN,'Boundary [%s] face indices [%s] belong to more than one BC and/or GridConnectivity'),
('S704',CGM.CHECK_FAIL,'Elements [%s] declared as boundary faces regarding ElementSizeBoundary should have one adjacent cell declared 0 in ParentElements'),

('S710',CGM.CHECK_WARN,'Node inconsistent with [%s] zone type'),

)

