# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGNS/NAV/T/Q7DiffWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Q7DiffWindow(object):
    def setupUi(self, Q7DiffWindow):
        Q7DiffWindow.setObjectName("Q7DiffWindow")
        Q7DiffWindow.resize(1124, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/cgSpy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7DiffWindow.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Q7DiffWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bLockScroll = QtWidgets.QPushButton(Q7DiffWindow)
        self.bLockScroll.setMinimumSize(QtCore.QSize(25, 25))
        self.bLockScroll.setMaximumSize(QtCore.QSize(25, 25))
        self.bLockScroll.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/lock-scroll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bLockScroll.setIcon(icon1)
        self.bLockScroll.setCheckable(True)
        self.bLockScroll.setChecked(True)
        self.bLockScroll.setObjectName("bLockScroll")
        self.horizontalLayout.addWidget(self.bLockScroll)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bZoomOut = QtWidgets.QToolButton(Q7DiffWindow)
        self.bZoomOut.setMinimumSize(QtCore.QSize(25, 25))
        self.bZoomOut.setMaximumSize(QtCore.QSize(25, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/level-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bZoomOut.setIcon(icon2)
        self.bZoomOut.setObjectName("bZoomOut")
        self.horizontalLayout.addWidget(self.bZoomOut)
        self.bZoomAll = QtWidgets.QPushButton(Q7DiffWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bZoomAll.sizePolicy().hasHeightForWidth())
        self.bZoomAll.setSizePolicy(sizePolicy)
        self.bZoomAll.setMinimumSize(QtCore.QSize(25, 25))
        self.bZoomAll.setMaximumSize(QtCore.QSize(25, 25))
        self.bZoomAll.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/level-all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bZoomAll.setIcon(icon3)
        self.bZoomAll.setObjectName("bZoomAll")
        self.horizontalLayout.addWidget(self.bZoomAll)
        self.bZoomIn = QtWidgets.QToolButton(Q7DiffWindow)
        self.bZoomIn.setMinimumSize(QtCore.QSize(25, 25))
        self.bZoomIn.setMaximumSize(QtCore.QSize(25, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/level-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bZoomIn.setIcon(icon4)
        self.bZoomIn.setObjectName("bZoomIn")
        self.horizontalLayout.addWidget(self.bZoomIn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bSaveDiff = QtWidgets.QToolButton(Q7DiffWindow)
        self.bSaveDiff.setMinimumSize(QtCore.QSize(25, 25))
        self.bSaveDiff.setMaximumSize(QtCore.QSize(25, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/select-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSaveDiff.setIcon(icon5)
        self.bSaveDiff.setObjectName("bSaveDiff")
        self.horizontalLayout.addWidget(self.bSaveDiff)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeviewA = Q7DiffTreeView(Q7DiffWindow)
        self.treeviewA.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.treeviewA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeviewA.setAutoScroll(False)
        self.treeviewA.setProperty("showDropIndicator", False)
        self.treeviewA.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.treeviewA.setIndentation(16)
        self.treeviewA.setRootIsDecorated(True)
        self.treeviewA.setUniformRowHeights(True)
        self.treeviewA.setExpandsOnDoubleClick(False)
        self.treeviewA.setObjectName("treeviewA")
        self.horizontalLayout_2.addWidget(self.treeviewA)
        self.verticalScrollBarA = QtWidgets.QScrollBar(Q7DiffWindow)
        self.verticalScrollBarA.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarA.setObjectName("verticalScrollBarA")
        self.horizontalLayout_2.addWidget(self.verticalScrollBarA)
        self.verticalScrollBarB = QtWidgets.QScrollBar(Q7DiffWindow)
        self.verticalScrollBarB.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarB.setObjectName("verticalScrollBarB")
        self.horizontalLayout_2.addWidget(self.verticalScrollBarB)
        self.treeviewB = Q7DiffTreeView(Q7DiffWindow)
        self.treeviewB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeviewB.setObjectName("treeviewB")
        self.horizontalLayout_2.addWidget(self.treeviewB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bBackControl = QtWidgets.QPushButton(Q7DiffWindow)
        self.bBackControl.setMinimumSize(QtCore.QSize(25, 25))
        self.bBackControl.setMaximumSize(QtCore.QSize(25, 25))
        self.bBackControl.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/top.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bBackControl.setIcon(icon6)
        self.bBackControl.setObjectName("bBackControl")
        self.horizontalLayout_3.addWidget(self.bBackControl)
        self.bInfo = QtWidgets.QPushButton(Q7DiffWindow)
        self.bInfo.setMinimumSize(QtCore.QSize(25, 25))
        self.bInfo.setMaximumSize(QtCore.QSize(25, 25))
        self.bInfo.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icons/help-view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInfo.setIcon(icon7)
        self.bInfo.setObjectName("bInfo")
        self.horizontalLayout_3.addWidget(self.bInfo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bPreviousMark = QtWidgets.QToolButton(Q7DiffWindow)
        self.bPreviousMark.setEnabled(True)
        self.bPreviousMark.setMinimumSize(QtCore.QSize(25, 25))
        self.bPreviousMark.setMaximumSize(QtCore.QSize(25, 25))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icons/node-sids-opened.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bPreviousMark.setIcon(icon8)
        self.bPreviousMark.setObjectName("bPreviousMark")
        self.horizontalLayout_3.addWidget(self.bPreviousMark)
        self.bUnmarkAll_1 = QtWidgets.QToolButton(Q7DiffWindow)
        self.bUnmarkAll_1.setMinimumSize(QtCore.QSize(25, 25))
        self.bUnmarkAll_1.setMaximumSize(QtCore.QSize(25, 25))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icons/node-sids-leaf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bUnmarkAll_1.setIcon(icon9)
        self.bUnmarkAll_1.setObjectName("bUnmarkAll_1")
        self.horizontalLayout_3.addWidget(self.bUnmarkAll_1)
        self.bNextMark = QtWidgets.QToolButton(Q7DiffWindow)
        self.bNextMark.setMinimumSize(QtCore.QSize(25, 25))
        self.bNextMark.setMaximumSize(QtCore.QSize(25, 25))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icons/node-sids-closed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bNextMark.setIcon(icon10)
        self.bNextMark.setObjectName("bNextMark")
        self.horizontalLayout_3.addWidget(self.bNextMark)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.bClose = QtWidgets.QPushButton(Q7DiffWindow)
        self.bClose.setObjectName("bClose")
        self.horizontalLayout_3.addWidget(self.bClose)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Q7DiffWindow)
        QtCore.QMetaObject.connectSlotsByName(Q7DiffWindow)

    def retranslateUi(self, Q7DiffWindow):
        _translate = QtCore.QCoreApplication.translate
        Q7DiffWindow.setWindowTitle(_translate("Q7DiffWindow", "Form"))
        self.bLockScroll.setToolTip(_translate("Q7DiffWindow", "Lock scrollbars together"))
        self.bZoomOut.setToolTip(_translate("Q7DiffWindow", "Collapse lowest tree level"))
        self.bZoomOut.setText(_translate("Q7DiffWindow", "..."))
        self.bZoomAll.setToolTip(_translate("Q7DiffWindow", "Expand all tree"))
        self.bZoomIn.setToolTip(_translate("Q7DiffWindow", "Expand lowest tree level"))
        self.bZoomIn.setText(_translate("Q7DiffWindow", "..."))
        self.bSaveDiff.setToolTip(_translate("Q7DiffWindow", "Save tree view snapshot"))
        self.bSaveDiff.setText(_translate("Q7DiffWindow", "..."))
        self.verticalScrollBarA.setToolTip(_translate("Q7DiffWindow", "DiffA file"))
        self.verticalScrollBarB.setToolTip(_translate("Q7DiffWindow", "DiffB file"))
        self.bBackControl.setToolTip(_translate("Q7DiffWindow", "Raise Control window"))
        self.bInfo.setToolTip(_translate("Q7DiffWindow", "Contextual help"))
        self.bPreviousMark.setToolTip(_translate("Q7DiffWindow", "Select previous marked node"))
        self.bPreviousMark.setText(_translate("Q7DiffWindow", "..."))
        self.bUnmarkAll_1.setToolTip(_translate("Q7DiffWindow", "Unmark all nodes"))
        self.bUnmarkAll_1.setText(_translate("Q7DiffWindow", "..."))
        self.bNextMark.setToolTip(_translate("Q7DiffWindow", "Select next marked node"))
        self.bNextMark.setText(_translate("Q7DiffWindow", "..."))
        self.bClose.setText(_translate("Q7DiffWindow", "Close"))
from CGNS.NAV.mdifftreeview import Q7DiffTreeView
from . import Res_rc
