# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGNS/NAV/T/Q7FormWindow.ui'
#
# Created: Fri Jun 24 13:58:00 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Q7FormWindow(object):
    def setupUi(self, Q7FormWindow):
        Q7FormWindow.setObjectName(_fromUtf8("Q7FormWindow"))
        Q7FormWindow.resize(550, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7FormWindow.sizePolicy().hasHeightForWidth())
        Q7FormWindow.setSizePolicy(sizePolicy)
        Q7FormWindow.setMinimumSize(QtCore.QSize(550, 600))
        Q7FormWindow.setMaximumSize(QtCore.QSize(999999, 999999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/cgSpy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7FormWindow.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Q7FormWindow)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bLockPanel = QtGui.QPushButton(Q7FormWindow)
        self.bLockPanel.setEnabled(False)
        self.bLockPanel.setMinimumSize(QtCore.QSize(25, 25))
        self.bLockPanel.setMaximumSize(QtCore.QSize(25, 25))
        self.bLockPanel.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/panel-lock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bLockPanel.setIcon(icon1)
        self.bLockPanel.setObjectName(_fromUtf8("bLockPanel"))
        self.horizontalLayout_2.addWidget(self.bLockPanel)
        self.ePath = QtGui.QLineEdit(Q7FormWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ePath.sizePolicy().hasHeightForWidth())
        self.ePath.setSizePolicy(sizePolicy)
        self.ePath.setMinimumSize(QtCore.QSize(510, 0))
        self.ePath.setObjectName(_fromUtf8("ePath"))
        self.horizontalLayout_2.addWidget(self.ePath)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(Q7FormWindow)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.eName = QtGui.QLineEdit(Q7FormWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eName.sizePolicy().hasHeightForWidth())
        self.eName.setSizePolicy(sizePolicy)
        self.eName.setMinimumSize(QtCore.QSize(220, 0))
        self.eName.setObjectName(_fromUtf8("eName"))
        self.horizontalLayout.addWidget(self.eName)
        self.label_3 = QtGui.QLabel(Q7FormWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.eType = QtGui.QComboBox(Q7FormWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eType.sizePolicy().hasHeightForWidth())
        self.eType.setSizePolicy(sizePolicy)
        self.eType.setMinimumSize(QtCore.QSize(200, 0))
        self.eType.setObjectName(_fromUtf8("eType"))
        self.horizontalLayout.addWidget(self.eType)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Q7FormWindow)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tData = QtGui.QWidget()
        self.tData.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tData.sizePolicy().hasHeightForWidth())
        self.tData.setSizePolicy(sizePolicy)
        self.tData.setObjectName(_fromUtf8("tData"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tData)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_3 = QtGui.QFrame(self.tData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 60))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(6, 40, 602, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.eItems = QtGui.QLineEdit(self.frame_3)
        self.eItems.setGeometry(QtCore.QRect(46, 35, 160, 22))
        self.eItems.setObjectName(_fromUtf8("eItems"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(5, 10, 32, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.cDataType = QtGui.QComboBox(self.frame_3)
        self.cDataType.setGeometry(QtCore.QRect(45, 5, 51, 23))
        self.cDataType.setObjectName(_fromUtf8("cDataType"))
        self.eDims = QtGui.QLineEdit(self.frame_3)
        self.eDims.setGeometry(QtCore.QRect(96, 5, 111, 24))
        self.eDims.setObjectName(_fromUtf8("eDims"))
        self.line = QtGui.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(213, 4, 16, 46))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(230, 10, 58, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_24 = QtGui.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(230, 35, 47, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.sMinH = QtGui.QSpinBox(self.frame_3)
        self.sMinH.setGeometry(QtCore.QRect(270, 6, 92, 22))
        self.sMinH.setObjectName(_fromUtf8("sMinH"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(370, 10, 58, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sMinV = QtGui.QSpinBox(self.frame_3)
        self.sMinV.setGeometry(QtCore.QRect(415, 5, 81, 22))
        self.sMinV.setObjectName(_fromUtf8("sMinV"))
        self.cRowColSize = QtGui.QComboBox(self.frame_3)
        self.cRowColSize.setGeometry(QtCore.QRect(270, 35, 196, 22))
        self.cRowColSize.setObjectName(_fromUtf8("cRowColSize"))
        self.bMinimize = QtGui.QPushButton(self.frame_3)
        self.bMinimize.setGeometry(QtCore.QRect(470, 34, 25, 25))
        self.bMinimize.setMinimumSize(QtCore.QSize(25, 25))
        self.bMinimize.setMaximumSize(QtCore.QSize(25, 25))
        self.bMinimize.setObjectName(_fromUtf8("bMinimize"))
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtGui.QFrame(self.tData)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tableView = Q7TableView(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(100, 100))
        self.tableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.tableView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView.setAutoFillBackground(False)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_12.addWidget(self.tableView)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tData, _fromUtf8(""))
        self.tFiles = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tFiles.sizePolicy().hasHeightForWidth())
        self.tFiles.setSizePolicy(sizePolicy)
        self.tFiles.setObjectName(_fromUtf8("tFiles"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tFiles)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.tFiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(5, 25, 59, 27))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.eDestPath = QtGui.QLineEdit(self.groupBox_3)
        self.eDestPath.setGeometry(QtCore.QRect(40, 24, 453, 27))
        self.eDestPath.setObjectName(_fromUtf8("eDestPath"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(6, 60, 45, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.eDestFile = QtGui.QLineEdit(self.groupBox_3)
        self.eDestFile.setGeometry(QtCore.QRect(40, 54, 299, 27))
        self.eDestFile.setObjectName(_fromUtf8("eDestFile"))
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(6, 121, 31, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(40, 115, 178, 27))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(385, 60, 58, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(453, 55, 39, 22))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.eDestDir = QtGui.QLineEdit(self.groupBox_3)
        self.eDestDir.setGeometry(QtCore.QRect(40, 84, 298, 27))
        self.eDestDir.setObjectName(_fromUtf8("eDestDir"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(5, 89, 45, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(8, 160, 492, 96))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 21, 151, 22))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(10, 43, 188, 22))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 66, 188, 22))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_18 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_18.setGeometry(QtCore.QRect(205, 20, 203, 22))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.cChildOfLink = QtGui.QCheckBox(self.groupBox)
        self.cChildOfLink.setGeometry(QtCore.QRect(205, 45, 232, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cChildOfLink.setFont(font)
        self.cChildOfLink.setObjectName(_fromUtf8("cChildOfLink"))
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tFiles, _fromUtf8(""))
        self.tText = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tText.sizePolicy().hasHeightForWidth())
        self.tText.setSizePolicy(sizePolicy)
        self.tText.setObjectName(_fromUtf8("tText"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tText)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cFortranOrderOff = QtGui.QCheckBox(self.tText)
        self.cFortranOrderOff.setObjectName(_fromUtf8("cFortranOrderOff"))
        self.horizontalLayout_4.addWidget(self.cFortranOrderOff)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.bRevert = QtGui.QPushButton(self.tText)
        self.bRevert.setMinimumSize(QtCore.QSize(25, 25))
        self.bRevert.setMaximumSize(QtCore.QSize(25, 25))
        self.bRevert.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/subtree-sids-failed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRevert.setIcon(icon2)
        self.bRevert.setObjectName(_fromUtf8("bRevert"))
        self.horizontalLayout_4.addWidget(self.bRevert)
        self.bCommit = QtGui.QPushButton(self.tText)
        self.bCommit.setMinimumSize(QtCore.QSize(25, 25))
        self.bCommit.setMaximumSize(QtCore.QSize(25, 25))
        self.bCommit.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/save-log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCommit.setIcon(icon3)
        self.bCommit.setObjectName(_fromUtf8("bCommit"))
        self.horizontalLayout_4.addWidget(self.bCommit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.eText = Q7PythonEditor(self.tText)
        self.eText.setObjectName(_fromUtf8("eText"))
        self.verticalLayout_10.addWidget(self.eText)
        self.tabWidget.addTab(self.tText, _fromUtf8(""))
        self.tPython = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tPython.sizePolicy().hasHeightForWidth())
        self.tPython.setSizePolicy(sizePolicy)
        self.tPython.setObjectName(_fromUtf8("tPython"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tPython)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_6 = QtGui.QFrame(self.tPython)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(550, 125))
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_11 = QtGui.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(5, 5, 33, 27))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_5 = QtGui.QComboBox(self.frame_6)
        self.comboBox_5.setGeometry(QtCore.QRect(55, 5, 101, 27))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_26 = QtGui.QLabel(self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(5, 37, 41, 27))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_20 = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_20.setGeometry(QtCore.QRect(55, 36, 171, 27))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.label_27 = QtGui.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(3, 65, 51, 27))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEdit_21 = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(55, 65, 171, 27))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.label_28 = QtGui.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(6, 91, 51, 27))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_22 = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(55, 96, 171, 26))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.checkBox_5 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_5.setGeometry(QtCore.QRect(255, 5, 161, 22))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_6.setGeometry(QtCore.QRect(255, 24, 161, 22))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_9 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_9.setGeometry(QtCore.QRect(254, 43, 161, 22))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.checkBox_21 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_21.setGeometry(QtCore.QRect(385, 7, 161, 22))
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.checkBox_7 = QtGui.QCheckBox(self.frame_6)
        self.checkBox_7.setGeometry(QtCore.QRect(384, 26, 161, 22))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.pushButton = QtGui.QPushButton(self.frame_6)
        self.pushButton.setGeometry(QtCore.QRect(332, 95, 161, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_7.addWidget(self.frame_6)
        self.plainTextEdit = Q7PythonEditor(self.tPython)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_7.addWidget(self.plainTextEdit)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tPython, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bBackControl = QtGui.QPushButton(Q7FormWindow)
        self.bBackControl.setMinimumSize(QtCore.QSize(25, 25))
        self.bBackControl.setMaximumSize(QtCore.QSize(25, 25))
        self.bBackControl.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/top.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bBackControl.setIcon(icon4)
        self.bBackControl.setObjectName(_fromUtf8("bBackControl"))
        self.horizontalLayout_3.addWidget(self.bBackControl)
        self.bInfo = QtGui.QPushButton(Q7FormWindow)
        self.bInfo.setMinimumSize(QtCore.QSize(25, 25))
        self.bInfo.setMaximumSize(QtCore.QSize(25, 25))
        self.bInfo.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/help-view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInfo.setIcon(icon5)
        self.bInfo.setObjectName(_fromUtf8("bInfo"))
        self.horizontalLayout_3.addWidget(self.bInfo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bClose = QtGui.QPushButton(Q7FormWindow)
        self.bClose.setObjectName(_fromUtf8("bClose"))
        self.horizontalLayout_3.addWidget(self.bClose)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Q7FormWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Q7FormWindow)

    def retranslateUi(self, Q7FormWindow):
        Q7FormWindow.setWindowTitle(_translate("Q7FormWindow", "Form", None))
        self.label_2.setText(_translate("Q7FormWindow", "Name", None))
        self.label_3.setText(_translate("Q7FormWindow", "Label", None))
        self.label_6.setText(_translate("Q7FormWindow", "Items", None))
        self.label.setText(_translate("Q7FormWindow", "Data", None))
        self.label_5.setText(_translate("Q7FormWindow", "min H", None))
        self.label_24.setText(_translate("Q7FormWindow", "Size", None))
        self.label_7.setText(_translate("Q7FormWindow", "min V", None))
        self.bMinimize.setText(_translate("Q7FormWindow", "fit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tData), _translate("Q7FormWindow", "Table", None))
        self.groupBox_3.setTitle(_translate("Q7FormWindow", "Node", None))
        self.label_9.setText(_translate("Q7FormWindow", "Path", None))
        self.label_10.setText(_translate("Q7FormWindow", "File", None))
        self.label_23.setText(_translate("Q7FormWindow", "Size", None))
        self.label_8.setText(_translate("Q7FormWindow", "Link level", None))
        self.label_13.setText(_translate("Q7FormWindow", "Dir", None))
        self.groupBox.setTitle(_translate("Q7FormWindow", "Status", None))
        self.checkBox_11.setText(_translate("Q7FormWindow", "Link not found", None))
        self.checkBox_8.setText(_translate("Q7FormWindow", "Destination File Read Only", None))
        self.checkBox_10.setText(_translate("Q7FormWindow", "Node not found in file", None))
        self.checkBox_18.setText(_translate("Q7FormWindow", "File load without following links", None))
        self.cChildOfLink.setText(_translate("Q7FormWindow", "Child of a linked node", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tFiles), _translate("Q7FormWindow", "Link", None))
        self.cFortranOrderOff.setText(_translate("Q7FormWindow", "Fortran order array is transposed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tText), _translate("Q7FormWindow", "Text", None))
        self.label_11.setText(_translate("Q7FormWindow", "Type", None))
        self.label_26.setText(_translate("Q7FormWindow", "Shape", None))
        self.label_27.setText(_translate("Q7FormWindow", "Strides", None))
        self.label_28.setText(_translate("Q7FormWindow", "Base", None))
        self.checkBox_5.setText(_translate("Q7FormWindow", "Data owner", None))
        self.checkBox_6.setText(_translate("Q7FormWindow", "Fortran order", None))
        self.checkBox_9.setText(_translate("Q7FormWindow", "Contiguous", None))
        self.checkBox_21.setText(_translate("Q7FormWindow", "View", None))
        self.checkBox_7.setText(_translate("Q7FormWindow", "C order", None))
        self.pushButton.setText(_translate("Q7FormWindow", "Run on NODE variable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tPython), _translate("Q7FormWindow", "Python", None))
        self.bClose.setText(_translate("Q7FormWindow", "Close", None))

from CGNS.NAV.weditors import Q7PythonEditor
from CGNS.NAV.mtable import Q7TableView
import Res_rc
