# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Q7FormWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFrame, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLayout, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QSpinBox, QTabWidget,
    QVBoxLayout, QWidget)

from CGNS.NAV.mtable import Q7TableView
from CGNS.NAV.weditors import Q7PythonEditor
from . import Res_rc

class Ui_Q7FormWindow(object):
    def setupUi(self, Q7FormWindow):
        if not Q7FormWindow.objectName():
            Q7FormWindow.setObjectName(u"Q7FormWindow")
        Q7FormWindow.resize(550, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7FormWindow.sizePolicy().hasHeightForWidth())
        Q7FormWindow.setSizePolicy(sizePolicy)
        Q7FormWindow.setMinimumSize(QSize(550, 600))
        Q7FormWindow.setMaximumSize(QSize(999999, 999999))
        icon = QIcon()
        icon.addFile(u":/images/icons/cgSpy.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Q7FormWindow.setWindowIcon(icon)
        self.verticalLayout_3 = QVBoxLayout(Q7FormWindow)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetFixedSize)
        self.bLockPanel = QPushButton(Q7FormWindow)
        self.bLockPanel.setObjectName(u"bLockPanel")
        self.bLockPanel.setEnabled(False)
        self.bLockPanel.setMinimumSize(QSize(25, 25))
        self.bLockPanel.setMaximumSize(QSize(25, 25))
        icon1 = QIcon()
        icon1.addFile(u":/images/icons/panel-lock.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bLockPanel.setIcon(icon1)

        self.horizontalLayout_2.addWidget(self.bLockPanel)

        self.ePath = QLineEdit(Q7FormWindow)
        self.ePath.setObjectName(u"ePath")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ePath.sizePolicy().hasHeightForWidth())
        self.ePath.setSizePolicy(sizePolicy1)
        self.ePath.setMinimumSize(QSize(510, 0))

        self.horizontalLayout_2.addWidget(self.ePath)


        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetFixedSize)
        self.label_2 = QLabel(Q7FormWindow)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout.addWidget(self.label_2)

        self.eName = QLineEdit(Q7FormWindow)
        self.eName.setObjectName(u"eName")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.eName.sizePolicy().hasHeightForWidth())
        self.eName.setSizePolicy(sizePolicy2)
        self.eName.setMinimumSize(QSize(220, 0))

        self.horizontalLayout.addWidget(self.eName)

        self.label_3 = QLabel(Q7FormWindow)
        self.label_3.setObjectName(u"label_3")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.label_3)

        self.eType = QComboBox(Q7FormWindow)
        self.eType.setObjectName(u"eType")
        sizePolicy2.setHeightForWidth(self.eType.sizePolicy().hasHeightForWidth())
        self.eType.setSizePolicy(sizePolicy2)
        self.eType.setMinimumSize(QSize(200, 0))

        self.horizontalLayout.addWidget(self.eType)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)


        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SetNoConstraint)
        self.tabWidget = QTabWidget(Q7FormWindow)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tData = QWidget()
        self.tData.setObjectName(u"tData")
        self.tData.setEnabled(True)
        sizePolicy.setHeightForWidth(self.tData.sizePolicy().hasHeightForWidth())
        self.tData.setSizePolicy(sizePolicy)
        self.verticalLayout_8 = QVBoxLayout(self.tData)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.frame_3 = QFrame(self.tData)
        self.frame_3.setObjectName(u"frame_3")
        sizePolicy2.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy2)
        self.frame_3.setMinimumSize(QSize(600, 60))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(6, 40, 602, 16))
        self.eItems = QLineEdit(self.frame_3)
        self.eItems.setObjectName(u"eItems")
        self.eItems.setGeometry(QRect(46, 35, 160, 22))
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(5, 10, 32, 16))
        self.cDataType = QComboBox(self.frame_3)
        self.cDataType.setObjectName(u"cDataType")
        self.cDataType.setGeometry(QRect(45, 5, 51, 23))
        self.eDims = QLineEdit(self.frame_3)
        self.eDims.setObjectName(u"eDims")
        self.eDims.setGeometry(QRect(96, 5, 111, 24))
        self.line = QFrame(self.frame_3)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(213, 4, 16, 46))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(230, 10, 58, 16))
        self.label_24 = QLabel(self.frame_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(230, 35, 47, 16))
        self.sMinH = QSpinBox(self.frame_3)
        self.sMinH.setObjectName(u"sMinH")
        self.sMinH.setGeometry(QRect(270, 6, 92, 22))
        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(370, 10, 58, 16))
        self.sMinV = QSpinBox(self.frame_3)
        self.sMinV.setObjectName(u"sMinV")
        self.sMinV.setGeometry(QRect(415, 5, 81, 22))
        self.cRowColSize = QComboBox(self.frame_3)
        self.cRowColSize.setObjectName(u"cRowColSize")
        self.cRowColSize.setGeometry(QRect(270, 35, 196, 22))
        self.bMinimize = QPushButton(self.frame_3)
        self.bMinimize.setObjectName(u"bMinimize")
        self.bMinimize.setGeometry(QRect(470, 34, 25, 25))
        self.bMinimize.setMinimumSize(QSize(25, 25))
        self.bMinimize.setMaximumSize(QSize(25, 25))

        self.verticalLayout.addWidget(self.frame_3)

        self.frame_5 = QFrame(self.tData)
        self.frame_5.setObjectName(u"frame_5")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy4)
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.verticalLayout_12 = QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.tableView = Q7TableView(self.frame_5)
        self.tableView.setObjectName(u"tableView")
        sizePolicy4.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy4)
        self.tableView.setMinimumSize(QSize(100, 100))
        self.tableView.viewport().setProperty(u"cursor", QCursor(Qt.CursorShape.CrossCursor))
        self.tableView.setLayoutDirection(Qt.LeftToRight)
        self.tableView.setAutoFillBackground(False)
        self.tableView.setSelectionMode(QAbstractItemView.ContiguousSelection)
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(False)

        self.verticalLayout_12.addWidget(self.tableView)


        self.verticalLayout.addWidget(self.frame_5)


        self.verticalLayout_8.addLayout(self.verticalLayout)

        self.tabWidget.addTab(self.tData, "")
        self.tFiles = QWidget()
        self.tFiles.setObjectName(u"tFiles")
        sizePolicy4.setHeightForWidth(self.tFiles.sizePolicy().hasHeightForWidth())
        self.tFiles.setSizePolicy(sizePolicy4)
        self.verticalLayout_9 = QVBoxLayout(self.tFiles)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.groupBox_3 = QGroupBox(self.tFiles)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(5, 25, 59, 27))
        self.eDestPath = QLineEdit(self.groupBox_3)
        self.eDestPath.setObjectName(u"eDestPath")
        self.eDestPath.setGeometry(QRect(40, 24, 453, 27))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(6, 60, 45, 17))
        self.eDestFile = QLineEdit(self.groupBox_3)
        self.eDestFile.setObjectName(u"eDestFile")
        self.eDestFile.setGeometry(QRect(40, 54, 299, 27))
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(6, 121, 31, 17))
        self.lineEdit_18 = QLineEdit(self.groupBox_3)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(40, 115, 178, 27))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(385, 60, 58, 16))
        self.lineEdit_2 = QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(453, 55, 39, 22))
        self.eDestDir = QLineEdit(self.groupBox_3)
        self.eDestDir.setObjectName(u"eDestDir")
        self.eDestDir.setGeometry(QRect(40, 84, 298, 27))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(5, 89, 45, 17))
        self.groupBox = QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(8, 160, 492, 96))
        self.checkBox_11 = QCheckBox(self.groupBox)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(10, 21, 151, 22))
        self.checkBox_8 = QCheckBox(self.groupBox)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(10, 43, 188, 22))
        self.checkBox_10 = QCheckBox(self.groupBox)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(10, 66, 188, 22))
        self.checkBox_18 = QCheckBox(self.groupBox)
        self.checkBox_18.setObjectName(u"checkBox_18")
        self.checkBox_18.setGeometry(QRect(205, 20, 203, 22))
        self.cChildOfLink = QCheckBox(self.groupBox)
        self.cChildOfLink.setObjectName(u"cChildOfLink")
        self.cChildOfLink.setGeometry(QRect(205, 45, 232, 21))
        font = QFont()
        font.setBold(True)
        self.cChildOfLink.setFont(font)

        self.verticalLayout_6.addWidget(self.groupBox_3)


        self.verticalLayout_9.addLayout(self.verticalLayout_6)

        self.tabWidget.addTab(self.tFiles, "")
        self.tText = QWidget()
        self.tText.setObjectName(u"tText")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.tText.sizePolicy().hasHeightForWidth())
        self.tText.setSizePolicy(sizePolicy5)
        self.verticalLayout_10 = QVBoxLayout(self.tText)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.cFortranOrderOff = QCheckBox(self.tText)
        self.cFortranOrderOff.setObjectName(u"cFortranOrderOff")

        self.horizontalLayout_4.addWidget(self.cFortranOrderOff)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_3)

        self.bRevert = QPushButton(self.tText)
        self.bRevert.setObjectName(u"bRevert")
        self.bRevert.setMinimumSize(QSize(25, 25))
        self.bRevert.setMaximumSize(QSize(25, 25))
        icon2 = QIcon()
        icon2.addFile(u":/images/icons/subtree-sids-failed.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bRevert.setIcon(icon2)

        self.horizontalLayout_4.addWidget(self.bRevert)

        self.bCommit = QPushButton(self.tText)
        self.bCommit.setObjectName(u"bCommit")
        self.bCommit.setMinimumSize(QSize(25, 25))
        self.bCommit.setMaximumSize(QSize(25, 25))
        icon3 = QIcon()
        icon3.addFile(u":/images/icons/save-log.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bCommit.setIcon(icon3)

        self.horizontalLayout_4.addWidget(self.bCommit)


        self.verticalLayout_10.addLayout(self.horizontalLayout_4)

        self.eText = Q7PythonEditor(self.tText)
        self.eText.setObjectName(u"eText")

        self.verticalLayout_10.addWidget(self.eText)

        self.tabWidget.addTab(self.tText, "")
        self.tPython = QWidget()
        self.tPython.setObjectName(u"tPython")
        sizePolicy4.setHeightForWidth(self.tPython.sizePolicy().hasHeightForWidth())
        self.tPython.setSizePolicy(sizePolicy4)
        self.verticalLayout_11 = QVBoxLayout(self.tPython)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_7 = QVBoxLayout()
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setSizeConstraint(QLayout.SetNoConstraint)
        self.frame_6 = QFrame(self.tPython)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy2.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy2)
        self.frame_6.setMinimumSize(QSize(550, 125))
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_11 = QLabel(self.frame_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(5, 5, 33, 27))
        self.comboBox_5 = QComboBox(self.frame_6)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(55, 5, 101, 27))
        self.label_26 = QLabel(self.frame_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(5, 37, 41, 27))
        self.lineEdit_20 = QLineEdit(self.frame_6)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(55, 36, 171, 27))
        self.label_27 = QLabel(self.frame_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(3, 65, 51, 27))
        self.lineEdit_21 = QLineEdit(self.frame_6)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(55, 65, 171, 27))
        self.label_28 = QLabel(self.frame_6)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(6, 91, 51, 27))
        self.lineEdit_22 = QLineEdit(self.frame_6)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(55, 96, 171, 26))
        self.checkBox_5 = QCheckBox(self.frame_6)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(255, 5, 161, 22))
        self.checkBox_6 = QCheckBox(self.frame_6)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(255, 24, 161, 22))
        self.checkBox_9 = QCheckBox(self.frame_6)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(254, 43, 161, 22))
        self.checkBox_21 = QCheckBox(self.frame_6)
        self.checkBox_21.setObjectName(u"checkBox_21")
        self.checkBox_21.setGeometry(QRect(385, 7, 161, 22))
        self.checkBox_7 = QCheckBox(self.frame_6)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(384, 26, 161, 22))
        self.pushButton = QPushButton(self.frame_6)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(332, 95, 161, 27))

        self.verticalLayout_7.addWidget(self.frame_6)

        self.plainTextEdit = Q7PythonEditor(self.tPython)
        self.plainTextEdit.setObjectName(u"plainTextEdit")

        self.verticalLayout_7.addWidget(self.plainTextEdit)


        self.verticalLayout_11.addLayout(self.verticalLayout_7)

        self.tabWidget.addTab(self.tPython, "")

        self.verticalLayout_2.addWidget(self.tabWidget)


        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetNoConstraint)
        self.bBackControl = QPushButton(Q7FormWindow)
        self.bBackControl.setObjectName(u"bBackControl")
        self.bBackControl.setMinimumSize(QSize(25, 25))
        self.bBackControl.setMaximumSize(QSize(25, 25))
        icon4 = QIcon()
        icon4.addFile(u":/images/icons/top.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bBackControl.setIcon(icon4)

        self.horizontalLayout_3.addWidget(self.bBackControl)

        self.bInfo = QPushButton(Q7FormWindow)
        self.bInfo.setObjectName(u"bInfo")
        self.bInfo.setMinimumSize(QSize(25, 25))
        self.bInfo.setMaximumSize(QSize(25, 25))
        icon5 = QIcon()
        icon5.addFile(u":/images/icons/help-view.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bInfo.setIcon(icon5)

        self.horizontalLayout_3.addWidget(self.bInfo)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.bClose = QPushButton(Q7FormWindow)
        self.bClose.setObjectName(u"bClose")

        self.horizontalLayout_3.addWidget(self.bClose)


        self.verticalLayout_3.addLayout(self.horizontalLayout_3)


        self.retranslateUi(Q7FormWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Q7FormWindow)
    # setupUi

    def retranslateUi(self, Q7FormWindow):
        Q7FormWindow.setWindowTitle(QCoreApplication.translate("Q7FormWindow", u"Form", None))
        self.bLockPanel.setText("")
        self.label_2.setText(QCoreApplication.translate("Q7FormWindow", u"Name", None))
        self.label_3.setText(QCoreApplication.translate("Q7FormWindow", u"Label", None))
        self.label_6.setText(QCoreApplication.translate("Q7FormWindow", u"Items", None))
        self.label.setText(QCoreApplication.translate("Q7FormWindow", u"Data", None))
        self.label_5.setText(QCoreApplication.translate("Q7FormWindow", u"min H", None))
        self.label_24.setText(QCoreApplication.translate("Q7FormWindow", u"Size", None))
        self.label_7.setText(QCoreApplication.translate("Q7FormWindow", u"min V", None))
        self.bMinimize.setText(QCoreApplication.translate("Q7FormWindow", u"fit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tData), QCoreApplication.translate("Q7FormWindow", u"Table", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Q7FormWindow", u"Node", None))
        self.label_9.setText(QCoreApplication.translate("Q7FormWindow", u"Path", None))
        self.label_10.setText(QCoreApplication.translate("Q7FormWindow", u"File", None))
        self.label_23.setText(QCoreApplication.translate("Q7FormWindow", u"Size", None))
        self.label_8.setText(QCoreApplication.translate("Q7FormWindow", u"Link level", None))
        self.label_13.setText(QCoreApplication.translate("Q7FormWindow", u"Dir", None))
        self.groupBox.setTitle(QCoreApplication.translate("Q7FormWindow", u"Status", None))
        self.checkBox_11.setText(QCoreApplication.translate("Q7FormWindow", u"Link not found", None))
        self.checkBox_8.setText(QCoreApplication.translate("Q7FormWindow", u"Destination File Read Only", None))
        self.checkBox_10.setText(QCoreApplication.translate("Q7FormWindow", u"Node not found in file", None))
        self.checkBox_18.setText(QCoreApplication.translate("Q7FormWindow", u"File load without following links", None))
        self.cChildOfLink.setText(QCoreApplication.translate("Q7FormWindow", u"Child of a linked node", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tFiles), QCoreApplication.translate("Q7FormWindow", u"Link", None))
        self.cFortranOrderOff.setText(QCoreApplication.translate("Q7FormWindow", u"Fortran order array is transposed", None))
        self.bRevert.setText("")
        self.bCommit.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tText), QCoreApplication.translate("Q7FormWindow", u"Text", None))
        self.label_11.setText(QCoreApplication.translate("Q7FormWindow", u"Type", None))
        self.label_26.setText(QCoreApplication.translate("Q7FormWindow", u"Shape", None))
        self.label_27.setText(QCoreApplication.translate("Q7FormWindow", u"Strides", None))
        self.label_28.setText(QCoreApplication.translate("Q7FormWindow", u"Base", None))
        self.checkBox_5.setText(QCoreApplication.translate("Q7FormWindow", u"Data owner", None))
        self.checkBox_6.setText(QCoreApplication.translate("Q7FormWindow", u"Fortran order", None))
        self.checkBox_9.setText(QCoreApplication.translate("Q7FormWindow", u"Contiguous", None))
        self.checkBox_21.setText(QCoreApplication.translate("Q7FormWindow", u"View", None))
        self.checkBox_7.setText(QCoreApplication.translate("Q7FormWindow", u"C order", None))
        self.pushButton.setText(QCoreApplication.translate("Q7FormWindow", u"Run on NODE variable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tPython), QCoreApplication.translate("Q7FormWindow", u"Python", None))
        self.bBackControl.setText("")
        self.bInfo.setText("")
        self.bClose.setText(QCoreApplication.translate("Q7FormWindow", u"Close", None))
    # retranslateUi

