# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Q7InfoWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QPushButton, QSizePolicy, QSpacerItem, QWidget)
from . import Res_rc

class Ui_Q7InfoWindow(object):
    def setupUi(self, Q7InfoWindow):
        if not Q7InfoWindow.objectName():
            Q7InfoWindow.setObjectName(u"Q7InfoWindow")
        Q7InfoWindow.setWindowModality(Qt.ApplicationModal)
        Q7InfoWindow.resize(715, 390)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7InfoWindow.sizePolicy().hasHeightForWidth())
        Q7InfoWindow.setSizePolicy(sizePolicy)
        Q7InfoWindow.setMinimumSize(QSize(715, 390))
        Q7InfoWindow.setMaximumSize(QSize(715, 390))
        self.gridLayout = QGridLayout(Q7InfoWindow)
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.bInfo = QPushButton(Q7InfoWindow)
        self.bInfo.setObjectName(u"bInfo")
        self.bInfo.setMinimumSize(QSize(25, 25))
        self.bInfo.setMaximumSize(QSize(25, 25))
        icon = QIcon()
        icon.addFile(u":/images/icons/help-view.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bInfo.setIcon(icon)

        self.horizontalLayout_2.addWidget(self.bInfo)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.bClose = QPushButton(Q7InfoWindow)
        self.bClose.setObjectName(u"bClose")

        self.horizontalLayout_2.addWidget(self.bClose)


        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SetNoConstraint)
        self.groupBox_2 = QGroupBox(Q7InfoWindow)
        self.groupBox_2.setObjectName(u"groupBox_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy1)
        self.groupBox_2.setMinimumSize(QSize(200, 0))
        self.groupBox_2.setMaximumSize(QSize(200, 16777215))
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 110, 181, 81))
        self.cHDF5 = QCheckBox(self.groupBox_4)
        self.cHDF5.setObjectName(u"cHDF5")
        self.cHDF5.setGeometry(QRect(10, 20, 94, 21))
        self.cHDF5.setCheckable(True)
        self.cADF = QCheckBox(self.groupBox_4)
        self.cADF.setObjectName(u"cADF")
        self.cADF.setGeometry(QRect(80, 20, 94, 21))
        self.cADF.setCheckable(True)
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 50, 91, 16))
        self.eVersionHDF5 = QLineEdit(self.groupBox_4)
        self.eVersionHDF5.setObjectName(u"eVersionHDF5")
        self.eVersionHDF5.setGeometry(QRect(100, 50, 71, 22))
        self.eVersionHDF5.setReadOnly(True)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 20, 58, 16))
        self.eVersion = QLineEdit(self.groupBox_2)
        self.eVersion.setObjectName(u"eVersion")
        self.eVersion.setGeometry(QRect(90, 20, 71, 22))
        self.eVersion.setReadOnly(True)
        self.groupBox_5 = QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 40, 181, 71))
        self.cREAD = QCheckBox(self.groupBox_5)
        self.cREAD.setObjectName(u"cREAD")
        self.cREAD.setGeometry(QRect(10, 20, 94, 21))
        self.cREAD.setCheckable(True)
        self.cMODIFY = QCheckBox(self.groupBox_5)
        self.cMODIFY.setObjectName(u"cMODIFY")
        self.cMODIFY.setGeometry(QRect(10, 40, 94, 21))
        self.cMODIFY.setCheckable(True)
        self.cConverted = QCheckBox(self.groupBox_2)
        self.cConverted.setObjectName(u"cConverted")
        self.cConverted.setGeometry(QRect(10, 200, 161, 21))
        self.cConverted.setCheckable(True)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 230, 161, 31))
        self.label_12.setWordWrap(True)

        self.horizontalLayout_3.addWidget(self.groupBox_2)

        self.groupBox_6 = QGroupBox(Q7InfoWindow)
        self.groupBox_6.setObjectName(u"groupBox_6")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy2)
        self.groupBox_6.setMinimumSize(QSize(220, 0))
        self.groupBox = QGroupBox(self.groupBox_6)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 130, 201, 131))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy3)
        self.groupBox.setMinimumSize(QSize(150, 0))
        self.cHasLinks = QCheckBox(self.groupBox)
        self.cHasLinks.setObjectName(u"cHasLinks")
        self.cHasLinks.setGeometry(QRect(10, 20, 86, 21))
        self.cHasLinks.setCheckable(False)
        self.cSameFS = QCheckBox(self.groupBox)
        self.cSameFS.setObjectName(u"cSameFS")
        self.cSameFS.setGeometry(QRect(10, 80, 161, 21))
        self.cSameFS.setCheckable(False)
        self.cBadLinks = QCheckBox(self.groupBox)
        self.cBadLinks.setObjectName(u"cBadLinks")
        self.cBadLinks.setGeometry(QRect(10, 100, 141, 20))
        self.cBadLinks.setCheckable(False)
        self.cModeProp = QCheckBox(self.groupBox)
        self.cModeProp.setObjectName(u"cModeProp")
        self.cModeProp.setGeometry(QRect(10, 60, 131, 21))
        self.cModeProp.setCheckable(False)
        self.cHasInt64 = QCheckBox(self.groupBox_6)
        self.cHasInt64.setObjectName(u"cHasInt64")
        self.cHasInt64.setGeometry(QRect(10, 40, 201, 21))
        self.cHasInt64.setCheckable(True)
        self.cNODATA = QCheckBox(self.groupBox_6)
        self.cNODATA.setObjectName(u"cNODATA")
        self.cNODATA.setGeometry(QRect(10, 20, 201, 21))
        self.cNODATA.setCheckable(True)
        self.cNoFollow = QCheckBox(self.groupBox_6)
        self.cNoFollow.setObjectName(u"cNoFollow")
        self.cNoFollow.setGeometry(QRect(20, 170, 191, 21))
        self.cNoFollow.setCheckable(False)
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 70, 111, 16))
        self.label_10 = QLabel(self.groupBox_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 100, 81, 16))
        self.eNodes = QLineEdit(self.groupBox_6)
        self.eNodes.setObjectName(u"eNodes")
        self.eNodes.setGeometry(QRect(120, 70, 91, 22))
        self.eNodes.setReadOnly(True)
        self.eDepth = QLineEdit(self.groupBox_6)
        self.eDepth.setObjectName(u"eDepth")
        self.eDepth.setGeometry(QRect(120, 100, 91, 22))
        self.eDepth.setReadOnly(True)

        self.horizontalLayout_3.addWidget(self.groupBox_6)

        self.groupBox_3 = QGroupBox(Q7InfoWindow)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy4)
        self.groupBox_3.setMinimumSize(QSize(250, 0))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 50, 81, 16))
        self.eFileSize = QLineEdit(self.groupBox_3)
        self.eFileSize.setObjectName(u"eFileSize")
        self.eFileSize.setGeometry(QRect(90, 20, 161, 22))
        self.eFileSize.setReadOnly(True)
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 58, 16))
        self.eMergeSize = QLineEdit(self.groupBox_3)
        self.eMergeSize.setObjectName(u"eMergeSize")
        self.eMergeSize.setGeometry(QRect(90, 50, 161, 22))
        self.eMergeSize.setReadOnly(True)
        self.eLastDate = QLineEdit(self.groupBox_3)
        self.eLastDate.setObjectName(u"eLastDate")
        self.eLastDate.setGeometry(QRect(90, 90, 161, 22))
        self.eLastDate.setReadOnly(True)
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 90, 81, 16))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 110, 71, 31))
        self.label_6.setWordWrap(True)
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 160, 58, 16))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 220, 58, 16))
        self.eModifDate = QLineEdit(self.groupBox_3)
        self.eModifDate.setObjectName(u"eModifDate")
        self.eModifDate.setGeometry(QRect(90, 120, 161, 22))
        self.eModifDate.setReadOnly(True)
        self.eOwner = QLineEdit(self.groupBox_3)
        self.eOwner.setObjectName(u"eOwner")
        self.eOwner.setGeometry(QRect(90, 160, 113, 22))
        self.eOwner.setReadOnly(True)
        self.eRights = QLineEdit(self.groupBox_3)
        self.eRights.setObjectName(u"eRights")
        self.eRights.setGeometry(QRect(90, 220, 113, 22))
        self.eRights.setReadOnly(True)
        self.eGroup = QLineEdit(self.groupBox_3)
        self.eGroup.setObjectName(u"eGroup")
        self.eGroup.setGeometry(QRect(90, 190, 113, 22))
        self.eGroup.setReadOnly(True)
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 190, 58, 16))
        self.bHasBeenModified = QPushButton(self.groupBox_3)
        self.bHasBeenModified.setObjectName(u"bHasBeenModified")
        self.bHasBeenModified.setEnabled(True)
        self.bHasBeenModified.setGeometry(QRect(4, 250, 251, 25))
        icon1 = QIcon()
        icon1.addFile(u":/images/icons/subtree-sids-failed.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bHasBeenModified.setIcon(icon1)
        self.bHasBeenModified.setCheckable(True)
        self.bHasBeenModified.setFlat(True)

        self.horizontalLayout_3.addWidget(self.groupBox_3)


        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.label = QLabel(Q7InfoWindow)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.eFilename = QLineEdit(Q7InfoWindow)
        self.eFilename.setObjectName(u"eFilename")
        self.eFilename.setReadOnly(True)

        self.horizontalLayout.addWidget(self.eFilename)


        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.eTmpFile = QLineEdit(Q7InfoWindow)
        self.eTmpFile.setObjectName(u"eTmpFile")
        self.eTmpFile.setReadOnly(True)

        self.gridLayout_2.addWidget(self.eTmpFile, 0, 1, 1, 1)

        self.label_13 = QLabel(Q7InfoWindow)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_2, 6, 0, 1, 1)


        self.retranslateUi(Q7InfoWindow)

        QMetaObject.connectSlotsByName(Q7InfoWindow)
    # setupUi

    def retranslateUi(self, Q7InfoWindow):
        Q7InfoWindow.setWindowTitle(QCoreApplication.translate("Q7InfoWindow", u"Form", None))
        self.bInfo.setText("")
        self.bClose.setText(QCoreApplication.translate("Q7InfoWindow", u"Close", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Q7InfoWindow", u"CGNS", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Q7InfoWindow", u"Format", None))
        self.cHDF5.setText(QCoreApplication.translate("Q7InfoWindow", u"HDF5", None))
        self.cADF.setText(QCoreApplication.translate("Q7InfoWindow", u"ADF", None))
        self.label_14.setText(QCoreApplication.translate("Q7InfoWindow", u"HDF5 Version", None))
        self.label_4.setText(QCoreApplication.translate("Q7InfoWindow", u"Version:", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Q7InfoWindow", u"Mode", None))
        self.cREAD.setText(QCoreApplication.translate("Q7InfoWindow", u"READ only", None))
        self.cMODIFY.setText(QCoreApplication.translate("Q7InfoWindow", u"MODIFY", None))
        self.cConverted.setText(QCoreApplication.translate("Q7InfoWindow", u"Is converted from ADF", None))
        self.label_12.setText(QCoreApplication.translate("Q7InfoWindow", u"The TMP file name below is the actual converted file.", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Q7InfoWindow", u"Contents", None))
        self.groupBox.setTitle(QCoreApplication.translate("Q7InfoWindow", u"Links", None))
        self.cHasLinks.setText(QCoreApplication.translate("Q7InfoWindow", u"Has links", None))
        self.cSameFS.setText(QCoreApplication.translate("Q7InfoWindow", u"Same file system", None))
        self.cBadLinks.setText(QCoreApplication.translate("Q7InfoWindow", u"Bad links detected", None))
        self.cModeProp.setText(QCoreApplication.translate("Q7InfoWindow", u"Mode propagated", None))
        self.cHasInt64.setText(QCoreApplication.translate("Q7InfoWindow", u"Has double integers (int64)", None))
        self.cNODATA.setText(QCoreApplication.translate("Q7InfoWindow", u"Partial data mode", None))
        self.cNoFollow.setText(QCoreApplication.translate("Q7InfoWindow", u"Links not followed", None))
        self.label_9.setText(QCoreApplication.translate("Q7InfoWindow", u"Number of nodes", None))
        self.label_10.setText(QCoreApplication.translate("Q7InfoWindow", u"Max depth", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Q7InfoWindow", u"Stat", None))
        self.label_3.setText(QCoreApplication.translate("Q7InfoWindow", u"Merge size", None))
        self.label_2.setText(QCoreApplication.translate("Q7InfoWindow", u"File size", None))
        self.label_5.setText(QCoreApplication.translate("Q7InfoWindow", u"Last access", None))
        self.label_6.setText(QCoreApplication.translate("Q7InfoWindow", u"Last modification", None))
        self.label_7.setText(QCoreApplication.translate("Q7InfoWindow", u"Owner", None))
        self.label_8.setText(QCoreApplication.translate("Q7InfoWindow", u"Rights", None))
        self.label_11.setText(QCoreApplication.translate("Q7InfoWindow", u"Group", None))
        self.bHasBeenModified.setText(QCoreApplication.translate("Q7InfoWindow", u"WARNING: File has changed on disk", None))
        self.label.setText(QCoreApplication.translate("Q7InfoWindow", u"File: ", None))
        self.label_13.setText(QCoreApplication.translate("Q7InfoWindow", u"TMP:", None))
    # retranslateUi

