# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGNS/NAV/T/Q7OptionsWindow.ui'
#
# Created: Tue Aug  9 11:46:10 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Q7OptionsWindow(object):
    def setupUi(self, Q7OptionsWindow):
        Q7OptionsWindow.setObjectName(_fromUtf8("Q7OptionsWindow"))
        Q7OptionsWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Q7OptionsWindow.resize(650, 364)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7OptionsWindow.sizePolicy().hasHeightForWidth())
        Q7OptionsWindow.setSizePolicy(sizePolicy)
        Q7OptionsWindow.setMinimumSize(QtCore.QSize(650, 364))
        Q7OptionsWindow.setMaximumSize(QtCore.QSize(650, 364))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/cgSpy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7OptionsWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Q7OptionsWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabs = QtGui.QTabWidget(Q7OptionsWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setMinimumSize(QtCore.QSize(630, 310))
        self.tabs.setMaximumSize(QtCore.QSize(630, 310))
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.__O_recursivetreedisplay = QtGui.QCheckBox(self.tab_1)
        self.__O_recursivetreedisplay.setGeometry(QtCore.QRect(10, 15, 274, 22))
        self.__O_recursivetreedisplay.setObjectName(_fromUtf8("__O_recursivetreedisplay"))
        self.__O_donotdisplaylargedata = QtGui.QCheckBox(self.tab_1)
        self.__O_donotdisplaylargedata.setGeometry(QtCore.QRect(10, 155, 274, 22))
        self.__O_donotdisplaylargedata.setObjectName(_fromUtf8("__O_donotdisplaylargedata"))
        self.__O_donotloadlargearrays = QtGui.QCheckBox(self.tab_1)
        self.__O_donotloadlargearrays.setGeometry(QtCore.QRect(10, 80, 274, 22))
        self.__O_donotloadlargearrays.setObjectName(_fromUtf8("__O_donotloadlargearrays"))
        self.label_1 = QtGui.QLabel(self.tab_1)
        self.label_1.setGeometry(QtCore.QRect(10, 35, 217, 27))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.__O_maxrecursionlevel = QtGui.QSpinBox(self.tab_1)
        self.__O_maxrecursionlevel.setGeometry(QtCore.QRect(235, 35, 71, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_maxrecursionlevel.setFont(font)
        self.__O_maxrecursionlevel.setMinimum(1)
        self.__O_maxrecursionlevel.setMaximum(99)
        self.__O_maxrecursionlevel.setProperty("value", 7)
        self.__O_maxrecursionlevel.setObjectName(_fromUtf8("__O_maxrecursionlevel"))
        self.__O_maxloaddatasize = QtGui.QSpinBox(self.tab_1)
        self.__O_maxloaddatasize.setEnabled(True)
        self.__O_maxloaddatasize.setGeometry(QtCore.QRect(235, 100, 71, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(10)
        self.__O_maxloaddatasize.setFont(font)
        self.__O_maxloaddatasize.setMinimum(-1)
        self.__O_maxloaddatasize.setMaximum(65535)
        self.__O_maxloaddatasize.setProperty("value", -1)
        self.__O_maxloaddatasize.setObjectName(_fromUtf8("__O_maxloaddatasize"))
        self.__O_filterhdffiles = QtGui.QCheckBox(self.tab_1)
        self.__O_filterhdffiles.setGeometry(QtCore.QRect(320, 10, 274, 22))
        self.__O_filterhdffiles.setObjectName(_fromUtf8("__O_filterhdffiles"))
        self.__O_filtercgnsfiles = QtGui.QCheckBox(self.tab_1)
        self.__O_filtercgnsfiles.setGeometry(QtCore.QRect(320, 90, 274, 22))
        self.__O_filtercgnsfiles.setObjectName(_fromUtf8("__O_filtercgnsfiles"))
        self.line = QtGui.QFrame(self.tab_1)
        self.line.setGeometry(QtCore.QRect(305, 10, 20, 261))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.__O_cgnsfileextension = QtGui.QPlainTextEdit(self.tab_1)
        self.__O_cgnsfileextension.setGeometry(QtCore.QRect(335, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_cgnsfileextension.setFont(font)
        self.__O_cgnsfileextension.setObjectName(_fromUtf8("__O_cgnsfileextension"))
        self.__O_hdffileextension = QtGui.QPlainTextEdit(self.tab_1)
        self.__O_hdffileextension.setGeometry(QtCore.QRect(335, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_hdffileextension.setFont(font)
        self.__O_hdffileextension.setObjectName(_fromUtf8("__O_hdffileextension"))
        self.label_23 = QtGui.QLabel(self.tab_1)
        self.label_23.setGeometry(QtCore.QRect(10, 175, 217, 27))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.__O_maxdisplaydatasize = QtGui.QSpinBox(self.tab_1)
        self.__O_maxdisplaydatasize.setGeometry(QtCore.QRect(235, 175, 71, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_maxdisplaydatasize.setFont(font)
        self.__O_maxdisplaydatasize.setMinimum(-1)
        self.__O_maxdisplaydatasize.setMaximum(1000)
        self.__O_maxdisplaydatasize.setProperty("value", -1)
        self.__O_maxdisplaydatasize.setObjectName(_fromUtf8("__O_maxdisplaydatasize"))
        self.label_9 = QtGui.QLabel(self.tab_1)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 217, 27))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabs.addTab(self.tab_1, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.__O_fileupdateremoveschildren = QtGui.QCheckBox(self.tab_8)
        self.__O_fileupdateremoveschildren.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.__O_fileupdateremoveschildren.setObjectName(_fromUtf8("__O_fileupdateremoveschildren"))
        self.tabs.addTab(self.tab_8, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.__O_addcurrentdirinsearch = QtGui.QCheckBox(self.tab_2)
        self.__O_addcurrentdirinsearch.setGeometry(QtCore.QRect(5, 10, 274, 22))
        self.__O_addcurrentdirinsearch.setObjectName(_fromUtf8("__O_addcurrentdirinsearch"))
        self.__O_addrootdirinsearch = QtGui.QCheckBox(self.tab_2)
        self.__O_addrootdirinsearch.setGeometry(QtCore.QRect(5, 35, 311, 22))
        self.__O_addrootdirinsearch.setObjectName(_fromUtf8("__O_addrootdirinsearch"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(5, 105, 546, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.__O_linksearchpathlist = QtGui.QPlainTextEdit(self.groupBox_2)
        self.__O_linksearchpathlist.setGeometry(QtCore.QRect(0, 25, 541, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_linksearchpathlist.setFont(font)
        self.__O_linksearchpathlist.setObjectName(_fromUtf8("__O_linksearchpathlist"))
        self.__O_followlinksatload = QtGui.QCheckBox(self.groupBox_2)
        self.__O_followlinksatload.setGeometry(QtCore.QRect(0, 95, 274, 22))
        self.__O_followlinksatload.setObjectName(_fromUtf8("__O_followlinksatload"))
        self.__O_stoploadbrokenlinks = QtGui.QCheckBox(self.groupBox_2)
        self.__O_stoploadbrokenlinks.setGeometry(QtCore.QRect(0, 120, 274, 22))
        self.__O_stoploadbrokenlinks.setObjectName(_fromUtf8("__O_stoploadbrokenlinks"))
        self.__O_donotfollowlinksatsave = QtGui.QCheckBox(self.groupBox_2)
        self.__O_donotfollowlinksatsave.setEnabled(False)
        self.__O_donotfollowlinksatsave.setGeometry(QtCore.QRect(0, 145, 274, 22))
        self.__O_donotfollowlinksatsave.setObjectName(_fromUtf8("__O_donotfollowlinksatsave"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(365, 15, 181, 26))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabs.addTab(self.tab_2, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_4.setGeometry(QtCore.QRect(5, 5, 546, 96))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.__O_profilesearchpathlist = QtGui.QPlainTextEdit(self.groupBox_4)
        self.__O_profilesearchpathlist.setGeometry(QtCore.QRect(0, 25, 541, 66))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_profilesearchpathlist.setFont(font)
        self.__O_profilesearchpathlist.setObjectName(_fromUtf8("__O_profilesearchpathlist"))
        self.__O_recursivesidspatternsload = QtGui.QCheckBox(self.tab_7)
        self.__O_recursivesidspatternsload.setGeometry(QtCore.QRect(5, 105, 274, 22))
        self.__O_recursivesidspatternsload.setObjectName(_fromUtf8("__O_recursivesidspatternsload"))
        self.tabs.addTab(self.tab_7, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.__O_checkonthefly = QtGui.QCheckBox(self.tab_6)
        self.__O_checkonthefly.setEnabled(False)
        self.__O_checkonthefly.setGeometry(QtCore.QRect(10, 10, 274, 22))
        self.__O_checkonthefly.setCheckable(True)
        self.__O_checkonthefly.setObjectName(_fromUtf8("__O_checkonthefly"))
        self.__O_forcesidslegacymapping = QtGui.QCheckBox(self.tab_6)
        self.__O_forcesidslegacymapping.setEnabled(False)
        self.__O_forcesidslegacymapping.setGeometry(QtCore.QRect(10, 30, 274, 22))
        self.__O_forcesidslegacymapping.setObjectName(_fromUtf8("__O_forcesidslegacymapping"))
        self.__O_forcefortranflag = QtGui.QCheckBox(self.tab_6)
        self.__O_forcefortranflag.setEnabled(False)
        self.__O_forcefortranflag.setGeometry(QtCore.QRect(10, 50, 274, 22))
        self.__O_forcefortranflag.setObjectName(_fromUtf8("__O_forcefortranflag"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_3.setGeometry(QtCore.QRect(5, 75, 546, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(10, 25, 271, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.cRecurseGrammarSearch = QtGui.QCheckBox(self.groupBox_3)
        self.cRecurseGrammarSearch.setEnabled(False)
        self.cRecurseGrammarSearch.setGeometry(QtCore.QRect(10, 50, 301, 21))
        self.cRecurseGrammarSearch.setCheckable(False)
        self.cRecurseGrammarSearch.setObjectName(_fromUtf8("cRecurseGrammarSearch"))
        self.__O_grammarsearchpathlist = QtGui.QPlainTextEdit(self.groupBox_3)
        self.__O_grammarsearchpathlist.setGeometry(QtCore.QRect(0, 130, 536, 66))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_grammarsearchpathlist.setFont(font)
        self.__O_grammarsearchpathlist.setObjectName(_fromUtf8("__O_grammarsearchpathlist"))
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(0, 95, 147, 51))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(385, 10, 111, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.__O_valkeylist = QtGui.QPlainTextEdit(self.tab_6)
        self.__O_valkeylist.setGeometry(QtCore.QRect(385, 30, 156, 156))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_valkeylist.setFont(font)
        self.__O_valkeylist.setObjectName(_fromUtf8("__O_valkeylist"))
        self.tabs.addTab(self.tab_6, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.__O_label_size = QtGui.QSpinBox(self.tab_3)
        self.__O_label_size.setGeometry(QtCore.QRect(395, 20, 46, 27))
        self.__O_label_size.setMinimum(6)
        self.__O_label_size.setMaximum(18)
        self.__O_label_size.setProperty("value", 10)
        self.__O_label_size.setObjectName(_fromUtf8("__O_label_size"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 25, 166, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.__O_label_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_label_bold.setGeometry(QtCore.QRect(455, 25, 86, 21))
        self.__O_label_bold.setText(_fromUtf8(""))
        self.__O_label_bold.setObjectName(_fromUtf8("__O_label_bold"))
        self.__O_label_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_label_italic.setGeometry(QtCore.QRect(500, 25, 86, 21))
        self.__O_label_italic.setText(_fromUtf8(""))
        self.__O_label_italic.setObjectName(_fromUtf8("__O_label_italic"))
        self.__O_label_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_label_family.setGeometry(QtCore.QRect(180, 20, 216, 26))
        self.__O_label_family.setObjectName(_fromUtf8("__O_label_family"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 55, 161, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_12 = QtGui.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(10, 85, 161, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(10, 115, 161, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(10, 145, 166, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(10, 175, 166, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(445, 5, 58, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(495, 5, 58, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.__O_button_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_button_family.setGeometry(QtCore.QRect(180, 50, 216, 26))
        self.__O_button_family.setObjectName(_fromUtf8("__O_button_family"))
        self.__O_edit_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_edit_family.setGeometry(QtCore.QRect(180, 80, 216, 26))
        self.__O_edit_family.setObjectName(_fromUtf8("__O_edit_family"))
        self.__O_table_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_table_family.setGeometry(QtCore.QRect(180, 110, 216, 26))
        self.__O_table_family.setObjectName(_fromUtf8("__O_table_family"))
        self.__O_nname_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_nname_family.setEnabled(False)
        self.__O_nname_family.setGeometry(QtCore.QRect(180, 140, 216, 26))
        self.__O_nname_family.setObjectName(_fromUtf8("__O_nname_family"))
        self.__O_rname_family = QtGui.QFontComboBox(self.tab_3)
        self.__O_rname_family.setGeometry(QtCore.QRect(180, 170, 216, 26))
        self.__O_rname_family.setObjectName(_fromUtf8("__O_rname_family"))
        self.__O_button_size = QtGui.QSpinBox(self.tab_3)
        self.__O_button_size.setGeometry(QtCore.QRect(395, 50, 46, 27))
        self.__O_button_size.setMinimum(6)
        self.__O_button_size.setMaximum(18)
        self.__O_button_size.setProperty("value", 10)
        self.__O_button_size.setObjectName(_fromUtf8("__O_button_size"))
        self.__O_edit_size = QtGui.QSpinBox(self.tab_3)
        self.__O_edit_size.setGeometry(QtCore.QRect(395, 80, 46, 27))
        self.__O_edit_size.setMinimum(6)
        self.__O_edit_size.setMaximum(18)
        self.__O_edit_size.setProperty("value", 10)
        self.__O_edit_size.setObjectName(_fromUtf8("__O_edit_size"))
        self.__O_table_size = QtGui.QSpinBox(self.tab_3)
        self.__O_table_size.setGeometry(QtCore.QRect(395, 110, 46, 27))
        self.__O_table_size.setMinimum(6)
        self.__O_table_size.setMaximum(18)
        self.__O_table_size.setProperty("value", 10)
        self.__O_table_size.setObjectName(_fromUtf8("__O_table_size"))
        self.__O_nname_size = QtGui.QSpinBox(self.tab_3)
        self.__O_nname_size.setEnabled(False)
        self.__O_nname_size.setGeometry(QtCore.QRect(395, 140, 46, 27))
        self.__O_nname_size.setMinimum(6)
        self.__O_nname_size.setMaximum(18)
        self.__O_nname_size.setProperty("value", 10)
        self.__O_nname_size.setObjectName(_fromUtf8("__O_nname_size"))
        self.__O_rname_size = QtGui.QSpinBox(self.tab_3)
        self.__O_rname_size.setGeometry(QtCore.QRect(395, 170, 46, 27))
        self.__O_rname_size.setMinimum(6)
        self.__O_rname_size.setMaximum(18)
        self.__O_rname_size.setProperty("value", 10)
        self.__O_rname_size.setObjectName(_fromUtf8("__O_rname_size"))
        self.__O_button_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_button_bold.setGeometry(QtCore.QRect(455, 55, 86, 21))
        self.__O_button_bold.setText(_fromUtf8(""))
        self.__O_button_bold.setObjectName(_fromUtf8("__O_button_bold"))
        self.__O_edit_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_edit_bold.setGeometry(QtCore.QRect(455, 85, 86, 21))
        self.__O_edit_bold.setText(_fromUtf8(""))
        self.__O_edit_bold.setObjectName(_fromUtf8("__O_edit_bold"))
        self.__O_table_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_table_bold.setGeometry(QtCore.QRect(455, 115, 86, 21))
        self.__O_table_bold.setText(_fromUtf8(""))
        self.__O_table_bold.setObjectName(_fromUtf8("__O_table_bold"))
        self.__O_nname_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_nname_bold.setEnabled(False)
        self.__O_nname_bold.setGeometry(QtCore.QRect(455, 145, 86, 21))
        self.__O_nname_bold.setText(_fromUtf8(""))
        self.__O_nname_bold.setObjectName(_fromUtf8("__O_nname_bold"))
        self.__O_rname_bold = QtGui.QCheckBox(self.tab_3)
        self.__O_rname_bold.setGeometry(QtCore.QRect(455, 175, 86, 21))
        self.__O_rname_bold.setText(_fromUtf8(""))
        self.__O_rname_bold.setObjectName(_fromUtf8("__O_rname_bold"))
        self.__O_button_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_button_italic.setGeometry(QtCore.QRect(500, 55, 86, 21))
        self.__O_button_italic.setText(_fromUtf8(""))
        self.__O_button_italic.setObjectName(_fromUtf8("__O_button_italic"))
        self.__O_edit_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_edit_italic.setGeometry(QtCore.QRect(500, 85, 86, 21))
        self.__O_edit_italic.setText(_fromUtf8(""))
        self.__O_edit_italic.setObjectName(_fromUtf8("__O_edit_italic"))
        self.__O_table_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_table_italic.setGeometry(QtCore.QRect(500, 115, 86, 21))
        self.__O_table_italic.setText(_fromUtf8(""))
        self.__O_table_italic.setObjectName(_fromUtf8("__O_table_italic"))
        self.__O_nname_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_nname_italic.setEnabled(False)
        self.__O_nname_italic.setGeometry(QtCore.QRect(500, 145, 86, 21))
        self.__O_nname_italic.setText(_fromUtf8(""))
        self.__O_nname_italic.setObjectName(_fromUtf8("__O_nname_italic"))
        self.__O_rname_italic = QtGui.QCheckBox(self.tab_3)
        self.__O_rname_italic.setGeometry(QtCore.QRect(500, 175, 86, 21))
        self.__O_rname_italic.setText(_fromUtf8(""))
        self.__O_rname_italic.setObjectName(_fromUtf8("__O_rname_italic"))
        self.bResetFonts = QtGui.QPushButton(self.tab_3)
        self.bResetFonts.setGeometry(QtCore.QRect(10, 215, 25, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.bResetFonts.sizePolicy().hasHeightForWidth())
        self.bResetFonts.setSizePolicy(sizePolicy)
        self.bResetFonts.setMinimumSize(QtCore.QSize(25, 25))
        self.bResetFonts.setMaximumSize(QtCore.QSize(25, 25))
        self.bResetFonts.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/undo-last-modification.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bResetFonts.setIcon(icon1)
        self.bResetFonts.setObjectName(_fromUtf8("bResetFonts"))
        self.tabs.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.__O_showtableindex = QtGui.QCheckBox(self.tab_4)
        self.__O_showtableindex.setGeometry(QtCore.QRect(10, 55, 274, 22))
        self.__O_showtableindex.setObjectName(_fromUtf8("__O_showtableindex"))
        self.__O_oneviewpertreenode = QtGui.QCheckBox(self.tab_4)
        self.__O_oneviewpertreenode.setGeometry(QtCore.QRect(320, 5, 274, 22))
        self.__O_oneviewpertreenode.setObjectName(_fromUtf8("__O_oneviewpertreenode"))
        self.__O_showcolumnindex = QtGui.QCheckBox(self.tab_4)
        self.__O_showcolumnindex.setGeometry(QtCore.QRect(10, 80, 274, 22))
        self.__O_showcolumnindex.setObjectName(_fromUtf8("__O_showcolumnindex"))
        self.__O_showhelpballoons = QtGui.QCheckBox(self.tab_4)
        self.__O_showhelpballoons.setGeometry(QtCore.QRect(10, 105, 274, 22))
        self.__O_showhelpballoons.setObjectName(_fromUtf8("__O_showhelpballoons"))
        self.__O_show1dasplain = QtGui.QCheckBox(self.tab_4)
        self.__O_show1dasplain.setGeometry(QtCore.QRect(10, 30, 274, 22))
        self.__O_show1dasplain.setObjectName(_fromUtf8("__O_show1dasplain"))
        self.__O_showsidsstatuscolumn = QtGui.QCheckBox(self.tab_4)
        self.__O_showsidsstatuscolumn.setGeometry(QtCore.QRect(10, 5, 274, 22))
        self.__O_showsidsstatuscolumn.setObjectName(_fromUtf8("__O_showsidsstatuscolumn"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 135, 217, 27))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.__O_maxlengthdatadisplay = QtGui.QSpinBox(self.tab_4)
        self.__O_maxlengthdatadisplay.setGeometry(QtCore.QRect(230, 135, 101, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_maxlengthdatadisplay.setFont(font)
        self.__O_maxlengthdatadisplay.setMinimum(1)
        self.__O_maxlengthdatadisplay.setMaximum(999999999)
        self.__O_maxlengthdatadisplay.setSingleStep(10)
        self.__O_maxlengthdatadisplay.setProperty("value", 700)
        self.__O_maxlengthdatadisplay.setObjectName(_fromUtf8("__O_maxlengthdatadisplay"))
        self.__O_transposearrayforview = QtGui.QCheckBox(self.tab_4)
        self.__O_transposearrayforview.setGeometry(QtCore.QRect(320, 30, 274, 22))
        self.__O_transposearrayforview.setObjectName(_fromUtf8("__O_transposearrayforview"))
        self.__O_autoexpand = QtGui.QCheckBox(self.tab_4)
        self.__O_autoexpand.setGeometry(QtCore.QRect(320, 55, 166, 21))
        self.__O_autoexpand.setObjectName(_fromUtf8("__O_autoexpand"))
        self.tabs.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 536, 171))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.__O_querynoexception = QtGui.QCheckBox(self.groupBox)
        self.__O_querynoexception.setGeometry(QtCore.QRect(5, 30, 246, 20))
        self.__O_querynoexception.setObjectName(_fromUtf8("__O_querynoexception"))
        self.checkBox = QtGui.QCheckBox(self.tab)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(15, 10, 331, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setGeometry(QtCore.QRect(15, 35, 331, 20))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.tabs.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_4 = QtGui.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(10, 15, 147, 27))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(10, 45, 147, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.__O_snapshotdirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_snapshotdirectory.setGeometry(QtCore.QRect(160, 45, 391, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_snapshotdirectory.setFont(font)
        self.__O_snapshotdirectory.setObjectName(_fromUtf8("__O_snapshotdirectory"))
        self.__O_queriesdirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_queriesdirectory.setGeometry(QtCore.QRect(160, 15, 391, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_queriesdirectory.setFont(font)
        self.__O_queriesdirectory.setObjectName(_fromUtf8("__O_queriesdirectory"))
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 75, 147, 27))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.__O_selectionlistdirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_selectionlistdirectory.setGeometry(QtCore.QRect(160, 75, 391, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_selectionlistdirectory.setFont(font)
        self.__O_selectionlistdirectory.setObjectName(_fromUtf8("__O_selectionlistdirectory"))
        self.label_10 = QtGui.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(10, 115, 147, 27))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.__O_adfconversioncom = QtGui.QLineEdit(self.tab_5)
        self.__O_adfconversioncom.setGeometry(QtCore.QRect(160, 115, 391, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_adfconversioncom.setFont(font)
        self.__O_adfconversioncom.setObjectName(_fromUtf8("__O_adfconversioncom"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(10, 145, 151, 27))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.__O_temporarydirectory = QtGui.QLineEdit(self.tab_5)
        self.__O_temporarydirectory.setGeometry(QtCore.QRect(160, 145, 391, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        self.__O_temporarydirectory.setFont(font)
        self.__O_temporarydirectory.setObjectName(_fromUtf8("__O_temporarydirectory"))
        self.line_2 = QtGui.QFrame(self.tab_5)
        self.line_2.setGeometry(QtCore.QRect(10, 180, 536, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.__O_activatemultithreading = QtGui.QCheckBox(self.tab_5)
        self.__O_activatemultithreading.setGeometry(QtCore.QRect(375, 195, 166, 21))
        self.__O_activatemultithreading.setObjectName(_fromUtf8("__O_activatemultithreading"))
        self.__O_navtrace = QtGui.QCheckBox(self.tab_5)
        self.__O_navtrace.setGeometry(QtCore.QRect(10, 195, 131, 21))
        self.__O_navtrace.setObjectName(_fromUtf8("__O_navtrace"))
        self.__O_chlonetrace = QtGui.QCheckBox(self.tab_5)
        self.__O_chlonetrace.setGeometry(QtCore.QRect(10, 215, 111, 21))
        self.__O_chlonetrace.setObjectName(_fromUtf8("__O_chlonetrace"))
        self.bResetIgnored = QtGui.QPushButton(self.tab_5)
        self.bResetIgnored.setGeometry(QtCore.QRect(15, 240, 166, 28))
        self.bResetIgnored.setObjectName(_fromUtf8("bResetIgnored"))
        self.tabs.addTab(self.tab_5, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabs)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bReset = QtGui.QPushButton(Q7OptionsWindow)
        self.bReset.setObjectName(_fromUtf8("bReset"))
        self.horizontalLayout.addWidget(self.bReset)
        self.bInfo = QtGui.QPushButton(Q7OptionsWindow)
        self.bInfo.setMinimumSize(QtCore.QSize(25, 25))
        self.bInfo.setMaximumSize(QtCore.QSize(25, 25))
        self.bInfo.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/help-view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInfo.setIcon(icon2)
        self.bInfo.setObjectName(_fromUtf8("bInfo"))
        self.horizontalLayout.addWidget(self.bInfo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bApply = QtGui.QPushButton(Q7OptionsWindow)
        self.bApply.setObjectName(_fromUtf8("bApply"))
        self.horizontalLayout.addWidget(self.bApply)
        self.bClose = QtGui.QPushButton(Q7OptionsWindow)
        self.bClose.setObjectName(_fromUtf8("bClose"))
        self.horizontalLayout.addWidget(self.bClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Q7OptionsWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Q7OptionsWindow)

    def retranslateUi(self, Q7OptionsWindow):
        Q7OptionsWindow.setWindowTitle(_translate("Q7OptionsWindow", "Form", None))
        self.__O_recursivetreedisplay.setText(_translate("Q7OptionsWindow", "Recursive tree display", None))
        self.__O_donotdisplaylargedata.setText(_translate("Q7OptionsWindow", "Do not dispay large data", None))
        self.__O_donotloadlargearrays.setText(_translate("Q7OptionsWindow", "Do not load large data arrays", None))
        self.label_1.setText(_translate("Q7OptionsWindow", "Max tree parse recursion level:", None))
        self.__O_filterhdffiles.setText(_translate("Q7OptionsWindow", "filter *.hdf files", None))
        self.__O_filtercgnsfiles.setText(_translate("Q7OptionsWindow", "filter *.cgns files", None))
        self.label_23.setText(_translate("Q7OptionsWindow", "Display nodes with data size below:", None))
        self.label_9.setText(_translate("Q7OptionsWindow", "Do not load node data if above:", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_1), _translate("Q7OptionsWindow", "Load", None))
        self.__O_fileupdateremoveschildren.setText(_translate("Q7OptionsWindow", "File update removes missing children", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_8), _translate("Q7OptionsWindow", "Save", None))
        self.__O_addcurrentdirinsearch.setToolTip(_translate("Q7OptionsWindow", "Set to always add the current directory as the first in the linked-to files search.", "Set to always add the current directory as the first in the linked-to files search."))
        self.__O_addcurrentdirinsearch.setText(_translate("Q7OptionsWindow", "Add current dir in link search path", None))
        self.__O_addrootdirinsearch.setText(_translate("Q7OptionsWindow", "Add file system root dir in link search path", None))
        self.groupBox_2.setTitle(_translate("Q7OptionsWindow", "Search paths", None))
        self.__O_followlinksatload.setText(_translate("Q7OptionsWindow", "Follow links during file load", None))
        self.__O_stoploadbrokenlinks.setText(_translate("Q7OptionsWindow", "Stop loading on broken link", None))
        self.__O_donotfollowlinksatsave.setText(_translate("Q7OptionsWindow", "Do not follow links during file save", None))
        self.pushButton.setText(_translate("Q7OptionsWindow", "Remove unreachable paths", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("Q7OptionsWindow", "Links", None))
        self.groupBox_4.setTitle(_translate("Q7OptionsWindow", "Search paths", None))
        self.__O_recursivesidspatternsload.setText(_translate("Q7OptionsWindow", "Recursive SIDS patterns load", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_7), _translate("Q7OptionsWindow", "Profiles", None))
        self.__O_checkonthefly.setText(_translate("Q7OptionsWindow", "Check on the fly", None))
        self.__O_forcesidslegacymapping.setText(_translate("Q7OptionsWindow", "Force SIDS legacy mapping", None))
        self.__O_forcefortranflag.setText(_translate("Q7OptionsWindow", "Force fortran flag in numpy arrays", None))
        self.groupBox_3.setTitle(_translate("Q7OptionsWindow", "CGNS.VAL parameters", None))
        self.label_31.setText(_translate("Q7OptionsWindow", "See also: Paths tab and grammars paths", None))
        self.cRecurseGrammarSearch.setText(_translate("Q7OptionsWindow", "Activate recursion search for grammars (long)", None))
        self.label_24.setText(_translate("Q7OptionsWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Search paths</span></p></body></html>", None))
        self.label_25.setText(_translate("Q7OptionsWindow", "Grammar keys", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_6), _translate("Q7OptionsWindow", "Checks", None))
        self.label.setText(_translate("Q7OptionsWindow", "label", None))
        self.label_3.setText(_translate("Q7OptionsWindow", "button", None))
        self.label_12.setText(_translate("Q7OptionsWindow", "text edit", None))
        self.label_26.setText(_translate("Q7OptionsWindow", "table (Form view)", None))
        self.label_27.setText(_translate("Q7OptionsWindow", "graphic (VTK view)", None))
        self.label_28.setText(_translate("Q7OptionsWindow", "node name (Tree view)", None))
        self.label_29.setText(_translate("Q7OptionsWindow", "Bold", None))
        self.label_30.setText(_translate("Q7OptionsWindow", "Italic", None))
        self.bResetFonts.setToolTip(_translate("Q7OptionsWindow", "Reset all fonts to default installation fonts", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("Q7OptionsWindow", "Fonts", None))
        self.__O_showtableindex.setText(_translate("Q7OptionsWindow", "Show table index", None))
        self.__O_oneviewpertreenode.setText(_translate("Q7OptionsWindow", "One view per tree/node", None))
        self.__O_showcolumnindex.setText(_translate("Q7OptionsWindow", "Show columns titles", None))
        self.__O_showhelpballoons.setToolTip(_translate("Q7OptionsWindow", "Shows the help balloon you are reading right now.", None))
        self.__O_showhelpballoons.setText(_translate("Q7OptionsWindow", "Show tooltips", None))
        self.__O_show1dasplain.setText(_translate("Q7OptionsWindow", "Show 1D values as Python plain types", None))
        self.__O_showsidsstatuscolumn.setText(_translate("Q7OptionsWindow", "Show SIDS status column", None))
        self.label_2.setText(_translate("Q7OptionsWindow", "Max length of data display in tree", None))
        self.__O_transposearrayforview.setText(_translate("Q7OptionsWindow", "Transpose arrays for view/edit", None))
        self.__O_autoexpand.setText(_translate("Q7OptionsWindow", "Auto expand tree view ", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("Q7OptionsWindow", "Windows", None))
        self.groupBox.setTitle(_translate("Q7OptionsWindow", "Debug", None))
        self.__O_querynoexception.setText(_translate("Q7OptionsWindow", "Do not catch any exception", None))
        self.checkBox.setText(_translate("Q7OptionsWindow", "Ignore queries operating modification of the tree", None))
        self.checkBox_2.setText(_translate("Q7OptionsWindow", "Add query results to previous query results", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("Q7OptionsWindow", "Queries", None))
        self.label_4.setText(_translate("Q7OptionsWindow", "User queries directory", None))
        self.label_5.setText(_translate("Q7OptionsWindow", "Snapshot directory", None))
        self.label_6.setText(_translate("Q7OptionsWindow", "Selection list directory", None))
        self.label_10.setText(_translate("Q7OptionsWindow", "ADF conversion", None))
        self.label_11.setText(_translate("Q7OptionsWindow", "Temporary directory", None))
        self.__O_activatemultithreading.setText(_translate("Q7OptionsWindow", "Activate Multi-threading", None))
        self.__O_navtrace.setText(_translate("Q7OptionsWindow", "CGNS.NAV trace", None))
        self.__O_chlonetrace.setText(_translate("Q7OptionsWindow", "CHLone trace", None))
        self.bResetIgnored.setText(_translate("Q7OptionsWindow", "Reset ignored messages", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), _translate("Q7OptionsWindow", "Other", None))
        self.bReset.setText(_translate("Q7OptionsWindow", "Reset", None))
        self.bApply.setText(_translate("Q7OptionsWindow", "Apply", None))
        self.bClose.setText(_translate("Q7OptionsWindow", "Close", None))

import Res_rc
