# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CGNS/NAV/T/Q7QueryWindow.ui'
#
# Created: Thu Jul  7 14:45:14 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Q7QueryWindow(object):
    def setupUi(self, Q7QueryWindow):
        Q7QueryWindow.setObjectName(_fromUtf8("Q7QueryWindow"))
        Q7QueryWindow.resize(715, 350)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7QueryWindow.sizePolicy().hasHeightForWidth())
        Q7QueryWindow.setSizePolicy(sizePolicy)
        Q7QueryWindow.setMinimumSize(QtCore.QSize(715, 350))
        Q7QueryWindow.setMaximumSize(QtCore.QSize(715, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/cgSpy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Q7QueryWindow.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Q7QueryWindow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bBackControl = QtGui.QPushButton(Q7QueryWindow)
        self.bBackControl.setMinimumSize(QtCore.QSize(25, 25))
        self.bBackControl.setMaximumSize(QtCore.QSize(25, 25))
        self.bBackControl.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/top.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bBackControl.setIcon(icon1)
        self.bBackControl.setObjectName(_fromUtf8("bBackControl"))
        self.horizontalLayout_2.addWidget(self.bBackControl)
        self.bInfo = QtGui.QPushButton(Q7QueryWindow)
        self.bInfo.setMinimumSize(QtCore.QSize(25, 25))
        self.bInfo.setMaximumSize(QtCore.QSize(25, 25))
        self.bInfo.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/help-view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInfo.setIcon(icon2)
        self.bInfo.setObjectName(_fromUtf8("bInfo"))
        self.horizontalLayout_2.addWidget(self.bInfo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.bClose = QtGui.QPushButton(Q7QueryWindow)
        self.bClose.setObjectName(_fromUtf8("bClose"))
        self.horizontalLayout_2.addWidget(self.bClose)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(Q7QueryWindow)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.cQueryGroup = QtGui.QComboBox(Q7QueryWindow)
        self.cQueryGroup.setEnabled(True)
        self.cQueryGroup.setObjectName(_fromUtf8("cQueryGroup"))
        self.horizontalLayout.addWidget(self.cQueryGroup)
        self.label = QtGui.QLabel(Q7QueryWindow)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cQueryName = QtGui.QComboBox(Q7QueryWindow)
        self.cQueryName.setMinimumSize(QtCore.QSize(300, 0))
        self.cQueryName.setEditable(True)
        self.cQueryName.setObjectName(_fromUtf8("cQueryName"))
        self.horizontalLayout.addWidget(self.cQueryName)
        self.bAdd = QtGui.QPushButton(Q7QueryWindow)
        self.bAdd.setMinimumSize(QtCore.QSize(25, 25))
        self.bAdd.setMaximumSize(QtCore.QSize(25, 25))
        self.bAdd.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/operate-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAdd.setIcon(icon3)
        self.bAdd.setObjectName(_fromUtf8("bAdd"))
        self.horizontalLayout.addWidget(self.bAdd)
        self.bDel = QtGui.QPushButton(Q7QueryWindow)
        self.bDel.setMinimumSize(QtCore.QSize(25, 25))
        self.bDel.setMaximumSize(QtCore.QSize(25, 25))
        self.bDel.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/operate-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDel.setIcon(icon4)
        self.bDel.setObjectName(_fromUtf8("bDel"))
        self.horizontalLayout.addWidget(self.bDel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bSaveAsScript = QtGui.QPushButton(Q7QueryWindow)
        self.bSaveAsScript.setMinimumSize(QtCore.QSize(25, 25))
        self.bSaveAsScript.setMaximumSize(QtCore.QSize(25, 25))
        self.bSaveAsScript.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/operate-edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSaveAsScript.setIcon(icon5)
        self.bSaveAsScript.setObjectName(_fromUtf8("bSaveAsScript"))
        self.horizontalLayout.addWidget(self.bSaveAsScript)
        self.bSave = QtGui.QPushButton(Q7QueryWindow)
        self.bSave.setMinimumSize(QtCore.QSize(25, 25))
        self.bSave.setMaximumSize(QtCore.QSize(25, 25))
        self.bSave.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/operate-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSave.setIcon(icon6)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.horizontalLayout.addWidget(self.bSave)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Q7QueryWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(695, 265))
        self.tabWidget.setMaximumSize(QtCore.QSize(695, 265))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.eText = Q7PythonEditor(self.tab)
        self.eText.setGeometry(QtCore.QRect(10, 40, 671, 191))
        self.eText.setObjectName(_fromUtf8("eText"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 671, 28))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cRequireUpdate = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.cRequireUpdate.setObjectName(_fromUtf8("cRequireUpdate"))
        self.horizontalLayout_4.addWidget(self.cRequireUpdate)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.bRevert = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.bRevert.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.bRevert.sizePolicy().hasHeightForWidth())
        self.bRevert.setSizePolicy(sizePolicy)
        self.bRevert.setMinimumSize(QtCore.QSize(25, 25))
        self.bRevert.setMaximumSize(QtCore.QSize(25, 25))
        self.bRevert.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/undo-at-most.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRevert.setIcon(icon7)
        self.bRevert.setObjectName(_fromUtf8("bRevert"))
        self.horizontalLayout_4.addWidget(self.bRevert)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.eQueryDoc = Q7DocEditor(self.tab_3)
        self.eQueryDoc.setGeometry(QtCore.QRect(10, 40, 671, 191))
        self.eQueryDoc.setObjectName(_fromUtf8("eQueryDoc"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 671, 28))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.bRevertDoc = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.bRevertDoc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.bRevertDoc.sizePolicy().hasHeightForWidth())
        self.bRevertDoc.setSizePolicy(sizePolicy)
        self.bRevertDoc.setMinimumSize(QtCore.QSize(25, 25))
        self.bRevertDoc.setMaximumSize(QtCore.QSize(25, 25))
        self.bRevertDoc.setText(_fromUtf8(""))
        self.bRevertDoc.setIcon(icon7)
        self.bRevertDoc.setObjectName(_fromUtf8("bRevertDoc"))
        self.horizontalLayout_5.addWidget(self.bRevertDoc)
        self.bCommitDoc = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.bCommitDoc.setEnabled(True)
        self.bCommitDoc.setMinimumSize(QtCore.QSize(25, 25))
        self.bCommitDoc.setMaximumSize(QtCore.QSize(25, 25))
        self.bCommitDoc.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/save-log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCommitDoc.setIcon(icon8)
        self.bCommitDoc.setObjectName(_fromUtf8("bCommitDoc"))
        self.horizontalLayout_5.addWidget(self.bCommitDoc)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 28))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bRun = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.bRun.sizePolicy().hasHeightForWidth())
        self.bRun.setSizePolicy(sizePolicy)
        self.bRun.setMinimumSize(QtCore.QSize(25, 25))
        self.bRun.setMaximumSize(QtCore.QSize(25, 25))
        self.bRun.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/operate-execute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bRun.setIcon(icon9)
        self.bRun.setObjectName(_fromUtf8("bRun"))
        self.horizontalLayout_3.addWidget(self.bRun)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.eUserVariable = QtGui.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eUserVariable.sizePolicy().hasHeightForWidth())
        self.eUserVariable.setSizePolicy(sizePolicy)
        self.eUserVariable.setObjectName(_fromUtf8("eUserVariable"))
        self.horizontalLayout_3.addWidget(self.eUserVariable)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_2.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/icons/select-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon10)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.eResult = Q7PythonEditor(self.tab_2)
        self.eResult.setGeometry(QtCore.QRect(10, 40, 671, 191))
        self.eResult.setObjectName(_fromUtf8("eResult"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 5, 1, 1, 1)

        self.retranslateUi(Q7QueryWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Q7QueryWindow)

    def retranslateUi(self, Q7QueryWindow):
        Q7QueryWindow.setWindowTitle(_translate("Q7QueryWindow", "Form", None))
        self.bClose.setText(_translate("Q7QueryWindow", "Close", None))
        self.label_2.setText(_translate("Q7QueryWindow", "Group:", None))
        self.cQueryGroup.setToolTip(_translate("Q7QueryWindow", "Label to caracterize a set of queries", None))
        self.label.setText(_translate("Q7QueryWindow", "Query:", None))
        self.cQueryName.setToolTip(_translate("Q7QueryWindow", "Query name", None))
        self.bAdd.setToolTip(_translate("Q7QueryWindow", "Add as a new query", None))
        self.bDel.setToolTip(_translate("Q7QueryWindow", "Delete the query", None))
        self.bSaveAsScript.setToolTip(_translate("Q7QueryWindow", "Write query as single stand-alone python script", None))
        self.bSave.setToolTip(_translate("Q7QueryWindow", "Save all queries in user profile directory", None))
        self.cRequireUpdate.setText(_translate("Q7QueryWindow", "Script modifies tree and requires all views to update", None))
        self.bRevert.setToolTip(_translate("Q7QueryWindow", "Revert to last saved text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Q7QueryWindow", "Python", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Q7QueryWindow", "Documentation", None))
        self.bRun.setToolTip(_translate("Q7QueryWindow", "Run query with args", None))
        self.label_3.setText(_translate("Q7QueryWindow", "Args:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Q7QueryWindow", "Result", None))

from CGNS.NAV.weditors import Q7DocEditor, Q7PythonEditor
import Res_rc
