# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Q7ToolsWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpacerItem, QSpinBox, QTabWidget, QVBoxLayout,
    QWidget)
from . import Res_rc

class Ui_Q7ToolsWindow(object):
    def setupUi(self, Q7ToolsWindow):
        if not Q7ToolsWindow.objectName():
            Q7ToolsWindow.setObjectName(u"Q7ToolsWindow")
        Q7ToolsWindow.setWindowModality(Qt.NonModal)
        Q7ToolsWindow.resize(580, 364)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Q7ToolsWindow.sizePolicy().hasHeightForWidth())
        Q7ToolsWindow.setSizePolicy(sizePolicy)
        Q7ToolsWindow.setMinimumSize(QSize(580, 364))
        Q7ToolsWindow.setMaximumSize(QSize(580, 364))
        icon = QIcon()
        icon.addFile(u":/images/icons/cgSpy.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Q7ToolsWindow.setWindowIcon(icon)
        self.verticalLayout = QVBoxLayout(Q7ToolsWindow)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.tabWidget = QTabWidget(Q7ToolsWindow)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.Queries = QWidget()
        self.Queries.setObjectName(u"Queries")
        self.label_15 = QLabel(self.Queries)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 25, 37, 25))
        self.cGroup = QComboBox(self.Queries)
        self.cGroup.setObjectName(u"cGroup")
        self.cGroup.setEnabled(True)
        self.cGroup.setGeometry(QRect(95, 25, 74, 21))
        self.label_16 = QLabel(self.Queries)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 55, 36, 25))
        self.cQuery = QComboBox(self.Queries)
        self.cQuery.setObjectName(u"cQuery")
        self.cQuery.setGeometry(QRect(95, 55, 378, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.cQuery.sizePolicy().hasHeightForWidth())
        self.cQuery.setSizePolicy(sizePolicy1)
        self.bOperateDoc = QPushButton(self.Queries)
        self.bOperateDoc.setObjectName(u"bOperateDoc")
        self.bOperateDoc.setGeometry(QRect(15, 55, 25, 25))
        self.bOperateDoc.setMinimumSize(QSize(25, 25))
        self.bOperateDoc.setMaximumSize(QSize(25, 25))
        icon1 = QIcon()
        icon1.addFile(u":/images/icons/operate-doc.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bOperateDoc.setIcon(icon1)
        self.spinBox = QSpinBox(self.Queries)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(190, 235, 53, 22))
        self.checkBox = QCheckBox(self.Queries)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QRect(20, 240, 171, 20))
        self.groupBox_2 = QGroupBox(self.Queries)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QRect(15, 94, 521, 131))
        self.radioButton = QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setEnabled(False)
        self.radioButton.setGeometry(QRect(15, 20, 261, 20))
        self.eUserVariable = QLineEdit(self.groupBox_2)
        self.eUserVariable.setObjectName(u"eUserVariable")
        self.eUserVariable.setGeometry(QRect(130, 70, 376, 21))
        sizePolicy1.setHeightForWidth(self.eUserVariable.sizePolicy().hasHeightForWidth())
        self.eUserVariable.setSizePolicy(sizePolicy1)
        self.radioButton_2 = QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setGeometry(QRect(15, 70, 92, 20))
        self.radioButton_3 = QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setEnabled(False)
        self.radioButton_3.setGeometry(QRect(15, 95, 131, 20))
        self.lineEdit = QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QRect(130, 95, 376, 21))
        self.radioButton_4 = QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setEnabled(False)
        self.radioButton_4.setGeometry(QRect(15, 45, 426, 20))
        self.pushButton = QPushButton(self.Queries)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(510, 55, 25, 25))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(25)
        sizePolicy2.setVerticalStretch(25)
        sizePolicy2.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy2)
        self.pushButton.setMinimumSize(QSize(25, 25))
        self.pushButton.setMaximumSize(QSize(25, 25))
        icon2 = QIcon()
        icon2.addFile(u":/images/icons/flag-none.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.bApplyBox = QFrame(self.Queries)
        self.bApplyBox.setObjectName(u"bApplyBox")
        self.bApplyBox.setGeometry(QRect(495, 235, 36, 36))
        self.bApplyBox.setFrameShape(QFrame.Box)
        self.bApplyBox.setFrameShadow(QFrame.Plain)
        self.bApplyBox.setLineWidth(2)
        self.bApply = QPushButton(self.bApplyBox)
        self.bApply.setObjectName(u"bApply")
        self.bApply.setGeometry(QRect(5, 5, 25, 25))
        self.bApply.setMinimumSize(QSize(25, 25))
        self.bApply.setMaximumSize(QSize(25, 25))
        icon3 = QIcon()
        icon3.addFile(u":/images/icons/operate-execute.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bApply.setIcon(icon3)
        self.tabWidget.addTab(self.Queries, "")
        self.search = QWidget()
        self.search.setObjectName(u"search")
        self.verticalLayoutWidget = QWidget(self.search)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(5, 5, 541, 271))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.groupBox = QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy3)
        self.bSaveAsQuery = QPushButton(self.groupBox)
        self.bSaveAsQuery.setObjectName(u"bSaveAsQuery")
        self.bSaveAsQuery.setGeometry(QRect(350, 235, 24, 24))
        self.bSaveAsQuery.setMinimumSize(QSize(24, 24))
        self.bSaveAsQuery.setMaximumSize(QSize(24, 24))
        icon4 = QIcon()
        icon4.addFile(u":/images/icons/operate-save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bSaveAsQuery.setIcon(icon4)
        self.eSaveAsQuery = QLineEdit(self.groupBox)
        self.eSaveAsQuery.setObjectName(u"eSaveAsQuery")
        self.eSaveAsQuery.setGeometry(QRect(80, 235, 261, 21))
        self.sLevel = QSlider(self.groupBox)
        self.sLevel.setObjectName(u"sLevel")
        self.sLevel.setGeometry(QRect(420, 100, 16, 56))
        self.sLevel.setMaximum(2)
        self.sLevel.setSliderPosition(1)
        self.sLevel.setOrientation(Qt.Vertical)
        self.sLevel.setInvertedAppearance(True)
        self.sLevel.setInvertedControls(True)
        self.sLevel.setTickPosition(QSlider.TicksAbove)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(360, 95, 53, 15))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(360, 120, 53, 15))
        font = QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(360, 145, 53, 15))
        self.gCriteria = QGroupBox(self.groupBox)
        self.gCriteria.setObjectName(u"gCriteria")
        self.gCriteria.setGeometry(QRect(10, 10, 336, 196))
        self.label_9 = QLabel(self.gCriteria)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(15, 30, 76, 16))
        self.eName = QLineEdit(self.gCriteria)
        self.eName.setObjectName(u"eName")
        self.eName.setGeometry(QRect(75, 25, 181, 21))
        self.cDataCheck = QGroupBox(self.gCriteria)
        self.cDataCheck.setObjectName(u"cDataCheck")
        self.cDataCheck.setEnabled(True)
        self.cDataCheck.setGeometry(QRect(10, 85, 316, 106))
        self.cDataCheck.setCheckable(True)
        self.cDataCheck.setChecked(False)
        self.cDataType = QComboBox(self.cDataCheck)
        self.cDataType.setObjectName(u"cDataType")
        self.cDataType.setGeometry(QRect(65, 40, 41, 22))
        self.label_11 = QLabel(self.cDataCheck)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 45, 76, 16))
        self.label_12 = QLabel(self.cDataCheck)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 75, 76, 16))
        self.eValue = QLineEdit(self.cDataCheck)
        self.eValue.setObjectName(u"eValue")
        self.eValue.setGeometry(QRect(65, 15, 181, 21))
        self.label_13 = QLabel(self.cDataCheck)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 20, 76, 16))
        self.eMaxSize = QSpinBox(self.cDataCheck)
        self.eMaxSize.setObjectName(u"eMaxSize")
        self.eMaxSize.setGeometry(QRect(65, 70, 81, 22))
        self.eMaxSize.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.eMaxSize.setValue(65)
        self.cRegexpValue = QPushButton(self.cDataCheck)
        self.cRegexpValue.setObjectName(u"cRegexpValue")
        self.cRegexpValue.setGeometry(QRect(250, 15, 24, 24))
        self.cRegexpValue.setMinimumSize(QSize(24, 24))
        self.cRegexpValue.setMaximumSize(QSize(24, 24))
        icon5 = QIcon()
        icon5.addFile(u":/images/icons/regexp.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.cRegexpValue.setIcon(icon5)
        self.cRegexpValue.setCheckable(True)
        self.cNotValue = QPushButton(self.cDataCheck)
        self.cNotValue.setObjectName(u"cNotValue")
        self.cNotValue.setGeometry(QRect(280, 15, 24, 24))
        self.cNotValue.setMinimumSize(QSize(24, 24))
        self.cNotValue.setMaximumSize(QSize(24, 24))
        icon6 = QIcon()
        icon6.addFile(u":/images/icons/delete.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.cNotValue.setIcon(icon6)
        self.cNotValue.setCheckable(True)
        self.cNotDataType = QPushButton(self.cDataCheck)
        self.cNotDataType.setObjectName(u"cNotDataType")
        self.cNotDataType.setGeometry(QRect(280, 45, 24, 24))
        self.cNotDataType.setMinimumSize(QSize(24, 24))
        self.cNotDataType.setMaximumSize(QSize(24, 24))
        self.cNotDataType.setIcon(icon6)
        self.cNotDataType.setCheckable(True)
        self.label_10 = QLabel(self.gCriteria)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(15, 60, 76, 16))
        self.cSIDStype = QComboBox(self.gCriteria)
        self.cSIDStype.setObjectName(u"cSIDStype")
        self.cSIDStype.setGeometry(QRect(75, 55, 181, 22))
        self.cSIDStype.setEditable(True)
        self.cRegexpName = QPushButton(self.gCriteria)
        self.cRegexpName.setObjectName(u"cRegexpName")
        self.cRegexpName.setGeometry(QRect(260, 25, 24, 24))
        self.cRegexpName.setMinimumSize(QSize(24, 24))
        self.cRegexpName.setMaximumSize(QSize(24, 24))
        self.cRegexpName.setIcon(icon5)
        self.cRegexpName.setCheckable(True)
        self.cNotName = QPushButton(self.gCriteria)
        self.cNotName.setObjectName(u"cNotName")
        self.cNotName.setGeometry(QRect(290, 25, 24, 24))
        self.cNotName.setMinimumSize(QSize(24, 24))
        self.cNotName.setMaximumSize(QSize(24, 24))
        self.cNotName.setIcon(icon6)
        self.cNotName.setCheckable(True)
        self.cRegexpSIDStype = QPushButton(self.gCriteria)
        self.cRegexpSIDStype.setObjectName(u"cRegexpSIDStype")
        self.cRegexpSIDStype.setGeometry(QRect(260, 55, 24, 24))
        self.cRegexpSIDStype.setMinimumSize(QSize(24, 24))
        self.cRegexpSIDStype.setMaximumSize(QSize(24, 24))
        self.cRegexpSIDStype.setIcon(icon5)
        self.cRegexpSIDStype.setCheckable(True)
        self.cNotSIDStype = QPushButton(self.gCriteria)
        self.cNotSIDStype.setObjectName(u"cNotSIDStype")
        self.cNotSIDStype.setGeometry(QRect(290, 55, 24, 24))
        self.cNotSIDStype.setMinimumSize(QSize(24, 24))
        self.cNotSIDStype.setMaximumSize(QSize(24, 24))
        self.cNotSIDStype.setIcon(icon6)
        self.cNotSIDStype.setCheckable(True)
        self.rAddToCurrent = QRadioButton(self.groupBox)
        self.rAddToCurrent.setObjectName(u"rAddToCurrent")
        self.rAddToCurrent.setGeometry(QRect(355, 15, 176, 20))
        self.rAddToCurrent.setChecked(True)
        self.rClearCurrent = QRadioButton(self.groupBox)
        self.rClearCurrent.setObjectName(u"rClearCurrent")
        self.rClearCurrent.setGeometry(QRect(355, 55, 171, 20))
        self.rWithinCurrent = QRadioButton(self.groupBox)
        self.rWithinCurrent.setObjectName(u"rWithinCurrent")
        self.rWithinCurrent.setGeometry(QRect(355, 35, 156, 20))
        self.bRunSearch = QPushButton(self.groupBox)
        self.bRunSearch.setObjectName(u"bRunSearch")
        self.bRunSearch.setGeometry(QRect(350, 175, 24, 24))
        self.bRunSearch.setMinimumSize(QSize(24, 24))
        self.bRunSearch.setMaximumSize(QSize(24, 24))
        self.bRunSearch.setIcon(icon3)
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 215, 516, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 240, 53, 15))
        self.bFindQuery = QPushButton(self.groupBox)
        self.bFindQuery.setObjectName(u"bFindQuery")
        self.bFindQuery.setGeometry(QRect(10, 235, 24, 24))
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(24)
        sizePolicy4.setVerticalStretch(24)
        sizePolicy4.setHeightForWidth(self.bFindQuery.sizePolicy().hasHeightForWidth())
        self.bFindQuery.setSizePolicy(sizePolicy4)
        self.bFindQuery.setMinimumSize(QSize(24, 24))
        self.bFindQuery.setMaximumSize(QSize(24, 24))
        icon7 = QIcon()
        icon7.addFile(u":/images/icons/zoompoint.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bFindQuery.setIcon(icon7)
        self.eWithLinks = QCheckBox(self.groupBox)
        self.eWithLinks.setObjectName(u"eWithLinks")
        self.eWithLinks.setGeometry(QRect(385, 180, 111, 20))
        self.eWithLinks.setChecked(True)

        self.verticalLayout_2.addWidget(self.groupBox)

        self.tabWidget.addTab(self.search, "")
        self.diff = QWidget()
        self.diff.setObjectName(u"diff")
        self.gdiff = QGroupBox(self.diff)
        self.gdiff.setObjectName(u"gdiff")
        self.gdiff.setGeometry(QRect(5, 5, 541, 266))
        self.label = QLabel(self.gdiff)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(25, 25, 58, 16))
        self.cAncestor = QComboBox(self.gdiff)
        self.cAncestor.setObjectName(u"cAncestor")
        self.cAncestor.setGeometry(QRect(15, 45, 81, 22))
        self.cVersionA = QComboBox(self.gdiff)
        self.cVersionA.setObjectName(u"cVersionA")
        self.cVersionA.setGeometry(QRect(140, 45, 81, 22))
        self.label_2 = QLabel(self.gdiff)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 25, 58, 16))
        self.cShowA = QCheckBox(self.gdiff)
        self.cShowA.setObjectName(u"cShowA")
        self.cShowA.setEnabled(False)
        self.cShowA.setGeometry(QRect(235, 45, 176, 21))
        self.cShowA.setCheckable(True)
        self.cShowA.setChecked(False)
        self.bDiff = QPushButton(self.gdiff)
        self.bDiff.setObjectName(u"bDiff")
        self.bDiff.setGeometry(QRect(395, 45, 25, 25))
        self.bDiff.setMinimumSize(QSize(25, 25))
        self.bDiff.setMaximumSize(QSize(25, 25))
        self.bDiff.setIcon(icon3)
        self.tabWidget.addTab(self.diff, "")
        self.merge = QWidget()
        self.merge.setObjectName(u"merge")
        self.gdiff_2 = QGroupBox(self.merge)
        self.gdiff_2.setObjectName(u"gdiff_2")
        self.gdiff_2.setEnabled(False)
        self.gdiff_2.setGeometry(QRect(5, 5, 541, 266))
        self.bMerge = QPushButton(self.gdiff_2)
        self.bMerge.setObjectName(u"bMerge")
        self.bMerge.setGeometry(QRect(415, 130, 25, 25))
        self.bMerge.setMinimumSize(QSize(25, 25))
        self.bMerge.setMaximumSize(QSize(25, 25))
        self.bMerge.setIcon(icon3)
        self.groupBox_5 = QGroupBox(self.gdiff_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(150, 20, 386, 81))
        self.cTreeA = QComboBox(self.groupBox_5)
        self.cTreeA.setObjectName(u"cTreeA")
        self.cTreeA.setGeometry(QRect(10, 20, 81, 22))
        self.rForceA = QRadioButton(self.groupBox_5)
        self.rForceA.setObjectName(u"rForceA")
        self.rForceA.setGeometry(QRect(160, 15, 201, 21))
        self.rAncestorA = QRadioButton(self.groupBox_5)
        self.rAncestorA.setObjectName(u"rAncestorA")
        self.rAncestorA.setGeometry(QRect(160, 35, 226, 21))
        self.ePrefixA = QLineEdit(self.groupBox_5)
        self.ePrefixA.setObjectName(u"ePrefixA")
        self.ePrefixA.setGeometry(QRect(10, 50, 76, 22))
        self.label_5 = QLabel(self.groupBox_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 50, 58, 16))
        self.groupBox_6 = QGroupBox(self.gdiff_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(150, 180, 386, 81))
        self.cTreeB = QComboBox(self.groupBox_6)
        self.cTreeB.setObjectName(u"cTreeB")
        self.cTreeB.setGeometry(QRect(10, 20, 81, 22))
        self.rForceB = QRadioButton(self.groupBox_6)
        self.rForceB.setObjectName(u"rForceB")
        self.rForceB.setGeometry(QRect(155, 15, 201, 21))
        self.rAncestorB = QRadioButton(self.groupBox_6)
        self.rAncestorB.setObjectName(u"rAncestorB")
        self.rAncestorB.setGeometry(QRect(155, 35, 226, 21))
        self.ePrefixB = QLineEdit(self.groupBox_6)
        self.ePrefixB.setObjectName(u"ePrefixB")
        self.ePrefixB.setGeometry(QRect(10, 50, 76, 22))
        self.label_6 = QLabel(self.groupBox_6)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(90, 55, 58, 16))
        self.groupBox_7 = QGroupBox(self.gdiff_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(5, 100, 381, 76))
        self.cTreeAncestor = QComboBox(self.groupBox_7)
        self.cTreeAncestor.setObjectName(u"cTreeAncestor")
        self.cTreeAncestor.setEnabled(False)
        self.cTreeAncestor.setGeometry(QRect(10, 30, 81, 22))
        self.rForceNone = QRadioButton(self.groupBox_7)
        self.rForceNone.setObjectName(u"rForceNone")
        self.rForceNone.setGeometry(QRect(115, 10, 216, 21))
        self.rAncestor = QRadioButton(self.groupBox_7)
        self.rAncestor.setObjectName(u"rAncestor")
        self.rAncestor.setGeometry(QRect(115, 30, 211, 21))
        self.cAutoMerge = QCheckBox(self.gdiff_2)
        self.cAutoMerge.setObjectName(u"cAutoMerge")
        self.cAutoMerge.setGeometry(QRect(450, 130, 86, 21))
        self.tabWidget.addTab(self.merge, "")

        self.horizontalLayout_2.addWidget(self.tabWidget)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.bInfo = QPushButton(Q7ToolsWindow)
        self.bInfo.setObjectName(u"bInfo")
        self.bInfo.setMinimumSize(QSize(25, 25))
        self.bInfo.setMaximumSize(QSize(25, 25))
        icon8 = QIcon()
        icon8.addFile(u":/images/icons/help-view.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bInfo.setIcon(icon8)

        self.horizontalLayout.addWidget(self.bInfo)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.bClose = QPushButton(Q7ToolsWindow)
        self.bClose.setObjectName(u"bClose")

        self.horizontalLayout.addWidget(self.bClose)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(Q7ToolsWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Q7ToolsWindow)
    # setupUi

    def retranslateUi(self, Q7ToolsWindow):
        Q7ToolsWindow.setWindowTitle(QCoreApplication.translate("Q7ToolsWindow", u"Form", None))
        self.label_15.setText(QCoreApplication.translate("Q7ToolsWindow", u"Group:", None))
        self.label_16.setText(QCoreApplication.translate("Q7ToolsWindow", u"Query:", None))
#if QT_CONFIG(tooltip)
        self.bOperateDoc.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Show Query doc", None))
#endif // QT_CONFIG(tooltip)
        self.bOperateDoc.setText("")
        self.checkBox.setText(QCoreApplication.translate("Q7ToolsWindow", u"Show predefined query #", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"Query arguments :", None))
        self.radioButton.setText(QCoreApplication.translate("Q7ToolsWindow", u"Use last selected value as arg", None))
        self.radioButton_2.setText(QCoreApplication.translate("Q7ToolsWindow", u"Plain value", None))
        self.radioButton_3.setText(QCoreApplication.translate("Q7ToolsWindow", u"Regexp value", None))
        self.radioButton_4.setText(QCoreApplication.translate("Q7ToolsWindow", u"Use ALL selected value as arg (loop on values and add selections)", None))
        self.pushButton.setText("")
#if QT_CONFIG(tooltip)
        self.bApply.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Run Query", None))
#endif // QT_CONFIG(tooltip)
        self.bApply.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Queries), QCoreApplication.translate("Q7ToolsWindow", u"Queries", None))
        self.groupBox.setTitle("")
#if QT_CONFIG(tooltip)
        self.bSaveAsQuery.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Save as a query", None))
#endif // QT_CONFIG(tooltip)
        self.bSaveAsQuery.setText("")
        self.label_7.setText(QCoreApplication.translate("Q7ToolsWindow", u"Ancestor", None))
        self.label_8.setText(QCoreApplication.translate("Q7ToolsWindow", u"Current", None))
        self.label_14.setText(QCoreApplication.translate("Q7ToolsWindow", u"Children", None))
        self.gCriteria.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"###", None))
        self.label_9.setText(QCoreApplication.translate("Q7ToolsWindow", u"name:", None))
        self.cDataCheck.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"Data", None))
        self.label_11.setText(QCoreApplication.translate("Q7ToolsWindow", u"type:", None))
        self.label_12.setText(QCoreApplication.translate("Q7ToolsWindow", u"max size:", None))
        self.label_13.setText(QCoreApplication.translate("Q7ToolsWindow", u"value:", None))
#if QT_CONFIG(tooltip)
        self.cRegexpValue.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"String is a regular expression", None))
#endif // QT_CONFIG(tooltip)
        self.cRegexpValue.setText("")
#if QT_CONFIG(tooltip)
        self.cNotValue.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Use all strings but this one", None))
#endif // QT_CONFIG(tooltip)
        self.cNotValue.setText("")
#if QT_CONFIG(tooltip)
        self.cNotDataType.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Use all strings but this one", None))
#endif // QT_CONFIG(tooltip)
        self.cNotDataType.setText("")
        self.label_10.setText(QCoreApplication.translate("Q7ToolsWindow", u"SIDS type:", None))
#if QT_CONFIG(tooltip)
        self.cRegexpName.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"String is a regular expression", None))
#endif // QT_CONFIG(tooltip)
        self.cRegexpName.setText("")
#if QT_CONFIG(tooltip)
        self.cNotName.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Use all strings but this one", None))
#endif // QT_CONFIG(tooltip)
        self.cNotName.setText("")
#if QT_CONFIG(tooltip)
        self.cRegexpSIDStype.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"String is a regular expression", None))
#endif // QT_CONFIG(tooltip)
        self.cRegexpSIDStype.setText("")
#if QT_CONFIG(tooltip)
        self.cNotSIDStype.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Use all strings but this one", None))
#endif // QT_CONFIG(tooltip)
        self.cNotSIDStype.setText("")
        self.rAddToCurrent.setText(QCoreApplication.translate("Q7ToolsWindow", u"Add to current selection", None))
        self.rClearCurrent.setText(QCoreApplication.translate("Q7ToolsWindow", u"Clear current selection first", None))
        self.rWithinCurrent.setText(QCoreApplication.translate("Q7ToolsWindow", u"Within current selection", None))
#if QT_CONFIG(tooltip)
        self.bRunSearch.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Run current selection criteria", None))
#endif // QT_CONFIG(tooltip)
        self.bRunSearch.setText("")
        self.label_19.setText(QCoreApplication.translate("Q7ToolsWindow", u"name:", None))
#if QT_CONFIG(tooltip)
        self.bFindQuery.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Load search query with this name", None))
#endif // QT_CONFIG(tooltip)
        self.bFindQuery.setText("")
        self.eWithLinks.setText(QCoreApplication.translate("Q7ToolsWindow", u"Include links", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search), QCoreApplication.translate("Q7ToolsWindow", u"Search", None))
        self.gdiff.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"All tree identifications use view number", None))
        self.label.setText(QCoreApplication.translate("Q7ToolsWindow", u"Version A", None))
#if QT_CONFIG(tooltip)
        self.cAncestor.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Select first tree to diff", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("Q7ToolsWindow", u"Version B", None))
        self.cShowA.setText(QCoreApplication.translate("Q7ToolsWindow", u"Show result on B view", None))
#if QT_CONFIG(tooltip)
        self.bDiff.setToolTip(QCoreApplication.translate("Q7ToolsWindow", u"Process the diff", None))
#endif // QT_CONFIG(tooltip)
        self.bDiff.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.diff), QCoreApplication.translate("Q7ToolsWindow", u"Diff", None))
        self.gdiff_2.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"All tree identifications use view number", None))
        self.bMerge.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"Version A", None))
        self.rForceA.setText(QCoreApplication.translate("Q7ToolsWindow", u"Force A values when different", None))
        self.rAncestorA.setText(QCoreApplication.translate("Q7ToolsWindow", u"A replaces the common ancestor", None))
        self.label_5.setText(QCoreApplication.translate("Q7ToolsWindow", u"Prefix", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"Version B", None))
        self.rForceB.setText(QCoreApplication.translate("Q7ToolsWindow", u"Force B values when different", None))
        self.rAncestorB.setText(QCoreApplication.translate("Q7ToolsWindow", u"B replaces the common ancestor", None))
        self.label_6.setText(QCoreApplication.translate("Q7ToolsWindow", u"Prefix", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("Q7ToolsWindow", u"Ancestor", None))
        self.rForceNone.setText(QCoreApplication.translate("Q7ToolsWindow", u"Keep both values when different", None))
        self.rAncestor.setText(QCoreApplication.translate("Q7ToolsWindow", u"Use common ancestor", None))
        self.cAutoMerge.setText(QCoreApplication.translate("Q7ToolsWindow", u"Auto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.merge), QCoreApplication.translate("Q7ToolsWindow", u"Merge", None))
        self.bInfo.setText("")
        self.bClose.setText(QCoreApplication.translate("Q7ToolsWindow", u"Close", None))
    # retranslateUi

