#!/usr/bin/env python
# -----------------------------------------------------------------------------
# pyS7 - CGNS/SIDS editor
# ONERA/DSNA - marc.poinot@onera.fr
# pyS7 - $Rev: 70 $ $Date: 2009-01-30 11:49:10 +0100 (Fri, 30 Jan 2009) $
# -----------------------------------------------------------------------------
# See file COPYING in the root directory of this Python module source
# tree for license information.
#
import S7.supervisor.s7check as s7s
import getopt
import sys
import os

from S7.version import __vid__

def usage():
  print """pyS7 v%s
  -P <profiles-paths> : override S7PROFILEPATH variable for profile search
                        path variable. It is a ':' separated list of paths.

  -h : help
  -v : verbose (trace)
  """%__vid__
  sys.exit(-1)

try:
  ppath=os.environ['S7PROFILEPATH']
except KeyError:
  ppath=""
  
try:
 opts, args = getopt.getopt(sys.argv[1:], "hvP:")
except getopt.GetoptError:
 usage()

output=None
verbose=False
recurse=False
olist=[]

for o, a in opts:
  if (o == "-P"): ppath=a
  if (o == "-v"): verbose=True
  if (o in ("-h", "--help")): usage()

s7s.run(args)

# --------------------------------------------------------------------
