#  -------------------------------------------------------------------------
#  pyCGNS - Python package for CFD General Notation System -
#  See license.txt file in the root directory of this Python module source  
#  -------------------------------------------------------------------------
#
"""
 CGNS.MAP module is the CGNS module interface to CHLone
  - now all the code is in CHLone and its CGNS/Python interface
  - contains only renaming and a CGNS.MAP test file
  - please refer to CHLone python module for documentation
"""
#
from EmbeddedCHLone import load
from EmbeddedCHLone import save
from EmbeddedCHLone import probe
from EmbeddedCHLone import CHLoneException as error
#
import EmbeddedCHLone as CHL
#
S2P_NONE = CHL.FNONE
S2P_ALL = CHL.FALL
S2P_TRACE = CHL.FTRACE
S2P_FOLLOWLINKS = CHL.FFOLLOWLINKS
S2P_DEBUG = CHL.FDEBUG
S2P_NODATA = CHL.FNODATA
S2P_MERGELINKS = 0
S2P_COMPRESS = CHL.FCOMPRESS
S2P_REVERSEDIMS = CHL.FREVERSEDIMS
S2P_OWNDATA = CHL.FOWNDATA
S2P_UPDATE = CHL.FUPDATE
S2P_DELETEMISSING = CHL.FDELETEMISSING
S2P_ALTERNATESIDS = CHL.FALTERNATESIDS
S2P_NOTRANSPOSE = 0
S2P_UPDATEONLY = CHL.FUPDATEONLY
S2P_FORTRANFLAG = CHL.FFORTRANFLAG
S2P_PROPAGATE = CHL.FPROPAGATE
S2P_DEFAULT = CHL.FDEFAULT
S2P_DEFAULTS = CHL.FDEFAULTS
S2P_KEEPLIST = CHL.FKEEPLIST
S2P_CHECKSUM = CHL.FCHECKSUM

S2P_LKOK = CHL.LKOK
S2P_LKFAIL = CHL.LKFAIL
S2P_LKBADSYNTAX = CHL.LKBADSYNTAX
S2P_LKNOFILE = CHL.LKNOFILE
S2P_LKFILENOREAD = CHL.LKFILENOREAD
S2P_LKNONODE = CHL.LKNONODE
S2P_LKLOOP = CHL.LKLOOP
S2P_LKIGNORED = CHL.LKIGNORED

NONE = CHL.FNONE
ALL = CHL.FALL
TRACE = CHL.FTRACE
FOLLOWLINKS = CHL.FFOLLOWLINKS
DEBUG = CHL.FDEBUG
NODATA = CHL.FNODATA
MERGELINKS = 0
COMPRESS = CHL.FCOMPRESS
REVERSEDIMS = CHL.FREVERSEDIMS
OWNDATA = CHL.FOWNDATA
UPDATE = CHL.FUPDATE
DELETEMISSING = CHL.FDELETEMISSING
ALTERNATESIDS = CHL.FALTERNATESIDS
NOTRANSPOSE = 0
UPDATEONLY = CHL.FUPDATEONLY
FORTRANFLAG = CHL.FFORTRANFLAG
PROPAGATE = CHL.FPROPAGATE
DEFAULT = CHL.FDEFAULT
DEFAULTS = CHL.FDEFAULTS
KEEPLIST = CHL.FKEEPLIST
CHECKSUM = CHL.FCHECKSUM

LKOK = CHL.LKOK
LKFAIL = CHL.LKFAIL
LKBADSYNTAX = CHL.LKBADSYNTAX
LKNOFILE = CHL.LKNOFILE
LKFILENOREAD = CHL.LKFILENOREAD
LKNONODE = CHL.LKNONODE
LKLOOP = CHL.LKLOOP
LKIGNORED = CHL.LKIGNORED

# --- last line
