# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
#  workflow_dispatch:
#  push:
#    branches: 
#      - master
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
    - uses: actions/checkout@v4
    - name: Install dev dependencies
      run: |
        yum -y install gcc
        export HDF5_VERSION=1.12.1
        curl -fsSLO "https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-${HDF5_VERSION%.*}/hdf5-$HDF5_VERSION/src/hdf5-$HDF5_VERSION.tar.gz"
        gunzip < hdf5-$HDF5_VERSION.tar.gz | tar xf -
        cd hdf5-$HDF5_VERSION
        export CFLAGS="-O3 -fPIC"
        ./configure --prefix=/usr/local --enable-static --disable-shared --enable-largefile --disable-fortran --disable-hl --without-szlib --without-zlib
        make
        make check -i               # run test suite.
        make install
        make check-install        # verify installation.
        /opt/python/cp310-cp310/bin/pip install twine auditwheel
        cd
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        git config --global safe.directory "*"
        bash .github/workflows/build-wheels.sh
        /opt/python/cp310-cp310/bin/python -m build --wheel --outdir buildwheel/
        /opt/python/cp310-cp310/bin/python -m build --sdist --outdir wheelhouse/
        /opt/python/cp310-cp310/bin/python -m twine upload wheelhouse/*
