#  ---------------------------------------------------------------------------
#  pyCGNS - Python package for CFD General Notation System -
#  See license.txt file in the root directory of this Python module source  
#  ---------------------------------------------------------------------------
#
import CGNSBase_t
import Zone_t
import ZoneBC_t
import BC_t
import DataClass_t
import Descriptor_t
import DimensionalUnits_t
import DimensionalExponents_t
import GridLocation_t
import PointList_t
import PointRange_t
import Rind_t
import DataConversion_t
import SimulationType_t
import Ordinal_t
import GridCoordinates_t
import DataArray_t
import DiscreteData_t
import Elements_t
import BCDataSet_t
import BCData_t
import BCProperty_t
import RotatingCoordinates_t
import ZoneGridConnectivity_t
import GridConnectivity1to1_t
import GridConnectivity_t
import GridConnectivityProperty_t
import AverageInterface_t
import OversetHoles_t
import FlowSolution_t
import FlowEquationSet_t
import GoverningEquations_t
import GasModel_t
import ThermalConductivityModel_t
import ThermalRelaxationModel_t
import ChemicalKineticModel_t
import EMElectricFieldModel_t
import EMMagneticFieldModel_t
import EMConductivityModel_t
import ViscosityModel_t
import TurbulenceClosure_t
import TurbulenceModel_t
import AxiSymmetry_t
import BaseIterativeData_t
import ZoneIterativeData_t
import RigidGridMotion_t
import ArbitraryGridMotion_t
import ReferenceState_t
import ConvergenceHistory_t
import IntegralData_t
import UserDefinedData_t
import Gravity_t
import Family_t
import FamilyName_t
import FamilyBC_t
import GeometryReference_t

profile = {
    'CGNSBase_t': CGNSBase_t.pattern,
    'Zone_t': Zone_t.pattern,
    'ZoneBC_t': ZoneBC_t.pattern,
    'BC_t': BC_t.pattern,
    'DataClass_t': DataClass_t.pattern,
    'Descriptor_t': Descriptor_t.pattern,
    'DimensionalUnits_t': DimensionalUnits_t.pattern,
    'DimensionalExponents_t': DimensionalExponents_t.pattern,
    'GridLocation_t': GridLocation_t.pattern,
    'PointList_t': PointList_t.pattern,
    'PointRange_t': PointRange_t.pattern,
    'Rind_t': Rind_t.pattern,
    'DataConversion_t': DataConversion_t.pattern,
    'SimulationType_t': SimulationType_t.pattern,
    'Ordinal_t': Ordinal_t.pattern,
    'GridCoordinates_t': GridCoordinates_t.pattern,
    'DataArray_t': DataArray_t.pattern,
    'DiscreteData_t': DiscreteData_t.pattern,
    'Elements_t': Elements_t.pattern,
    'BCDataSet_t': BCDataSet_t.pattern,
    'BCData_t': BCData_t.pattern,
    'BCProperty_t': BCProperty_t.pattern,
    'RotatingCoordinates_t': RotatingCoordinates_t.pattern,
    'ZoneGridConnectivity_t': ZoneGridConnectivity_t.pattern,
    'GridConnectivity1to1_t': GridConnectivity1to1_t.pattern,
    'GridConnectivity_t': GridConnectivity_t.pattern,
    'GridConnectivityProperty_t': GridConnectivityProperty_t.pattern,
    'AverageInterface_t': AverageInterface_t.pattern,
    'OversetHoles_t': OversetHoles_t.pattern,
    'FlowSolution_t': FlowSolution_t.pattern,
    'FlowEquationSet_t': FlowEquationSet_t.pattern,
    'GoverningEquations_t': GoverningEquations_t.pattern,
    'GasModel_t': GasModel_t.pattern,
    'ThermalConductivityModel_t': ThermalConductivityModel_t.pattern,
    'ThermalRelaxationModel_t': ThermalRelaxationModel_t.pattern,
    'ChemicalKineticModel_t': ChemicalKineticModel_t.pattern,
    'EMElectricFieldModel_t': EMElectricFieldModel_t.pattern,
    'EMMagneticFieldModel_t': EMMagneticFieldModel_t.pattern,
    'EMConductivityModel_t': EMConductivityModel_t.pattern,
    'ViscosityModel_t': ViscosityModel_t.pattern,
    'TurbulenceClosure_t': TurbulenceClosure_t.pattern,
    'TurbulenceModel_t': TurbulenceModel_t.pattern,
    'AxiSymmetry_t': AxiSymmetry_t.pattern,
    'BaseIterativeData_t': BaseIterativeData_t.pattern,
    'ZoneIterativeData_t': ZoneIterativeData_t.pattern,
    'RigidGridMotion_t': RigidGridMotion_t.pattern,
    'ArbitraryGridMotion_t': ArbitraryGridMotion_t.pattern,
    'ReferenceState_t': ReferenceState_t.pattern,
    'ConvergenceHistory_t': ConvergenceHistory_t.pattern,
    'IntegralData_t': IntegralData_t.pattern,
    'UserDefinedData_t': UserDefinedData_t.pattern,
    'Gravity_t': Gravity_t.pattern,
    'Family_t': Family_t.pattern,
    'FamilyName_t': FamilyName_t.pattern,
    'FamilyBC_t': FamilyBC_t.pattern,
    'GeometryReference_t': GeometryReference_t.pattern,
}
#
